### ISSUE TITLE
Ausgabe funktioniert nicht mehr. 

### ISSUE THREAD

**Issue by emddummi** [ioBroker/ioBroker.sayit#100]
**Describe the bug**  
Habe mich gewundert warum ich seit Tagen keine Ansage mehr bekomme. Hab nun mitbekommen das einfach nichts passiert. Version 1.11.1

**Versions:**  
 - Adapter version: 1.11.1
 - JS-Controller version: 3.1.6
 - Node version: 10.20.1
 - Operating system: Debian Buster

**Additional context**  
Ich kann im Log keinen Fehler finden. Habe auf Debug gestellt und alles sieht normal aus. Habe es mit 2 verschiedenen Home Geräten probiert.

**Comment by Apollon77** [comment]
Mal ein Downgrade versucht? Gehen ältere versionen?

**Comment by emddummi** [comment]
Also bei Version 1.9.6 gleiches Verhalten.
Ich kann auch aus den Objekten heraus nicht die URL für die mp3 aufrufen. Sollte man das können?

**Comment by Apollon77** [comment]
die URL hat hart den Web port 8082 drin ... wenn Dein WebAdapter einen anderen Port hat musst Du das manuell anpassen.

ALso liegt es wohl eher nicht an der Version sondern an Google?

**Comment by emddummi** [comment]
Mit dem Update auf 1.11.2 läuft es wieder... Also egal was, danke!
