### ISSUE TITLE
No sound from the google Home

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.sayit#109]
The adapter seems to be working but if I edit the datapoint text nothing is played by the google home.
The log shows some errors after not playing:

`sayit.0	2020-10-26 11:18:45.595	info	(9978) Set "chromecast.0.Wohnung.player.announcement to {"url":"http://192.168.178.3:8082/state/sayit.0.tts.mp3","volume":30}
sayit.0	2020-10-26 11:18:45.574	info	(9978) Copied file "/opt/iobroker/iobroker-data/sayit/sayit.0.say.mp3" to "/opt/iobroker/cache/8afb3653e3f221116ae6511f02e56ef5.mp3"
sayit.0	2020-10-26 11:18:45.354	info	(9978) saying: versuch 1
sayit.0	2020-10-26 11:18:44.350	info	(9978) Set "chromecast.0.Wohnung.player.announcement to {"url":"http://192.168.178.3:8082/state/sayit.0.tts.mp3","volume":30}
sayit.0	2020-10-26 11:18:44.216	info	(9978) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3
sayit.0	2020-10-26 11:17:08.122	info	(9978) All files uploaded
sayit.0	2020-10-26 11:17:07.987	info	(9978) Upload announce mp3 files
sayit.0	2020-10-26 11:17:07.952	info	(9978) starting. Version 1.12.0 in /opt/iobroker/node_modules/iobroker.sayit, node: v12.19.0, js-controller: 3.1.6
sayit.0	2020-10-26 11:17:01.146	info	(9555) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
sayit.0	2020-10-26 11:17:00.643	info	(9555) stopping...
sayit.0	2020-10-26 11:13:29.337	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.335	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.331	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.324	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.323	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.314	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.305	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.296	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.295	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.280	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.279	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.278	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.261	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.260	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.241	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.232	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:29.224	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.711	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.709	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.707	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.705	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.703	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.701	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.699	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.696	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.692	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.689	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.676	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.669	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.666	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.663	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.662	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.658	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.656	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.653	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.652	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.649	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.647	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.646	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.645	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.640	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.637	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.633	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.628	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.627	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.620	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.614	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.609	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.606	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.600	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.598	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.593	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.589	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.585	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.581	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.576	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.572	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.567	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.379	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.378	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.378	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.354	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.353	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.352	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.331	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.329	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.310	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:13:13.309	error	(9555) Error on MDNS discovery: Error: getaddrinfo -3008
sayit.0	2020-10-26 11:12:39.764	info	(9555) Set "chromecast.0.WohnzimmerHub.player.announcement to {"url":"http://192.168.178.3:8082/state/sayit.0.tts.mp3","volume":70}
sayit.0	2020-10-26 11:12:39.759	info	(9555) saying: test
sayit.0	2020-10-26 11:12:17.054	info	(9555) Set "chromecast.0.WohnzimmerHub.player.announcement to {"url":"http://192.168.178.3:8082/state/sayit.0.tts.mp3","volume":70}
sayit.0	2020-10-26 11:12:16.977	info	(9555) saying: test
sayit.0	2020-10-26 11:11:31.291	info	(9555) All files uploaded
sayit.0	2020-10-26 11:11:31.190	info	(9555) Upload announce mp3 files
sayit.0	2020-10-26 11:11:31.144	info	(9555) starting. Version 1.12.0 in /opt/iobroker/node_modules/iobroker.sayit, node: v12.19.0, js-controller: 3.1.6
sayit.0	2020-10-26 11:11:22.909	info	(9260) stopping...
`
The adapter and system configs are:

![Screenshot 2020-10-26 at 11 31 13](https://user-images.githubusercontent.com/59663011/97162142-137a4e00-177f-11eb-9949-b4682f24a18c.png)

![Screenshot 2020-10-26 at 11 37 35](https://user-images.githubusercontent.com/59663011/97162902-217c9e80-1780-11eb-839d-08567350c373.png)

![Screenshot 2020-10-26 at 11 38 55](https://user-images.githubusercontent.com/59663011/97162966-3bb67c80-1780-11eb-9f20-5660366f2ed0.png)

![Screenshot 2020-10-26 at 11 39 05](https://user-images.githubusercontent.com/59663011/97162986-43762100-1780-11eb-87b2-16f74a36c7e5.png)

**Comment by Apollon77** [comment]
> Error on MDNS discovery: Error: getaddrinfo -3008 

mostly refernce to a network issue finding the device, Make sure it is there and mdns/udp is passed correctly

**Comment by Dragon0501** [comment]
Problem solved! Was my fault! Instance of Chromecast adapter was stopped... Restartet and problem solved.
