### ISSUE TITLE
Sayit > MPD, wrong volume value is transmitted

### ISSUE THREAD

**Issue by Alex18081** [ioBroker/ioBroker.sayit#110]
Bei volume änderung wird an mpd immer das gleiche wert übermittelt.

Beispiel
1. Sayit neugestrtet und eine ansage mit bestimten volume (z.b. 70) an mpd geschikt - geht ohne problemen, volume wird richtig übertragen
2. eine erneute ansage mit neuen volumen wert (50) an mpd geschikt - neue ansage wird am mpd übermittelt aber mit dem falschen volume wert (immer noch 70)
alle weitere versuche werden immer mit gleichen wert übertragaen, bis Sayit neugstrtartet wird.

**Comment by dimaindahood** [comment]
Auch wenn die Antwort etwas spät kommt. Wenn du unter Objekte bei "text" den Wert z.B. auf de;20;hi setzt dann wird auf Deutsch mit Lautstärke 20 der Text "hi" abgespielt. 
Auch über Blockly funktioniert es mit der Lautstärke. 
Aber wenn du bei "volume" den Wert einstellst dann wird dieser ignoriert. Schein ein Bug zu sein.
