### ISSUE TITLE
Store data for sayit.0.tts.ogg as string because no other valid type found (state not existing)

### ISSUE THREAD

**Issue by RESDE** [ioBroker/ioBroker.sayit#114]
SQL Adapter is finding old "halos" from old say.it states although the adapter has been deleted propperly (both as instance and the adapter in the repository)
Which cleaning is manually necessary to get say it completely of my current iobroker installation?

**Comment by Apollon77** [comment]
What is admin showing? Any other sayit objects/states? Normally the js.cntroller deletes an instance completely
