### ISSUE TITLE
Sayit spricht Ansagen doppelt

### ISSUE THREAD

**Issue by pjo12345** [ioBroker/ioBroker.sayit#119]
Wenn man den Adapter per Blockly oder JS anspricht und auf Chromecast wiedergibt, dann werden alle Ansagen doppelt gesprochen.

**Comment by thommicom** [comment]
Was war die Lösung?

**Comment by pjo12345** [comment]
Moin! War mehr oder weniger mein Fehler. Ich hatte das mit Blockly
programmiert und bei dem Textbaustein Variablen und Leerzeilen drin, weil
ich das einfach vom Textbaustein für die Telegram Ausgabe kopiert hatte.
Nachdem ich die Leerzeile entfernt hatte, war das mit den doppelten Ansagen
weg.
Die doppelte Ansage trat nicht immer auf. Ob diese Leerzeilen jetzt 100%ig
dran Schuld waren, weiß ich nicht. Aber es tritt nicht mehr auf. Ich hänge
mal ein Bild an, damit Du weißt was ich meine. Das Bild zeigt die
Telegram-Ausgabe.

Gruß Marko


thommicom <notifications@github.com> schrieb am Fr., 5. Feb. 2021, 16:59:

**Comment by thommicom** [comment]
Danke dir.
Die Telegrammnachrichten werden interessanterweise nur einmal gesendet. Von daher denke ich, dass es am sayit selbst liegen müsste. Bekomme es aber nicht zum greifen. Nach der iobroker neu gestartet ist, tritt der "Fehler" zunächst nicht auf. 

Ich die Nachrichten sende ich an den Chromcastadapter. Den "Fehler" vermute ich eher hier oder im sayit, als im Blockly.

**Comment by pjo12345** [comment]
An den Chromecast Adapter sende ich die Nachricht auch. Also bei mir tritt
es jetzt nicht mehr auf, nachdem ich die Nachrichten "aufgeräumt" habe.

thommicom <notifications@github.com> schrieb am Sa., 6. Feb. 2021, 12:41:
