### ISSUE TITLE
Bindung oder ip-Adresse anstatt Browser-Instanz 

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sayit#128]
Kann man auch ein Bindung zu einem iobroker-Objekt eingeben bei der Browser-Instanz, z.B.
{javascript.0.Sonstige....}

oder

Wäre erst auch möglich die IP-Adresse des Rechners an zugegeben wo der Text abgespielt werden soll.
(dies wäre noch besser).

**Comment by Apollon77** [comment]
Ich verstehe das issue nicht. Bitte genauer spezifizieren

**Comment by bahnuhr** [comment]
In sayit wird in der config die browser-instanz eingegeben. Dadurch kann man steuern, auf welchem PC der Text wiedergegeben wird.
Ich möchte nun diese ID in einem Objekt eingeben, die ich dann per Script verändern kann.
Oder alternativ
Die IP des PC in der config eingeben, damit gezielt der PC angesteuert wird mit dieser IP.

**Comment by bahnuhr** [comment]
weitere Info:
Ich habe im Wohnzimmer ein Win10-Tablet.
Für VIS benutze ich edge. Aber edge im kiosk mode ändert bei Neustart die browser ID von vis.
Lösung a)
Die ID wird von VIS in ein Objekt geschrieben, die ich dann irgendwie in sayit reinbekommen muss.
Lösung b)
In sayit wird die IP des PC angegeben wo der Text ausgegeben werden soll.

Lösung b) wäre die beste Idee.
mfg
Dieter

**Comment by bahnuhr** [comment]
Das Problem besteht weiterhin.
Eine Lösung/Umsetzung wäre gut.

**Comment by GermanBluefox** [comment]
Browser kann keine IPs sehen. Nur ioBroker IP ist sichtbar.

**Comment by bahnuhr** [comment]
Hallo Bluefox,
das wäre die Lösung:
Lösung b)
In sayit wird die IP des PC angegeben wo der Text ausgegeben werden soll.

Da muss der Browser keine IP sehen; diese wird ja in sayit eingegeben.
mfg

**Comment by GermanBluefox** [comment]
> In sayit wird die IP des PC angegeben wo der Text ausgegeben werden soll.

Ist unmöglich. Da der Sound im Browser abgespielt wird, kennt der Browser die eigene IP Adresse nicht.

**Comment by bahnuhr** [comment]
Dann Lösung a)
Lösung a)
Die ID wird von VIS in ein Objekt geschrieben, die ich dann irgendwie in sayit reinbekommen muss.

Müsste doch möglich sein.
