### ISSUE TITLE
[Feature Request] Airplay Support 

### ISSUE THREAD

**Issue by TheMBeat** [ioBroker/ioBroker.sayit#129]
**Is your feature request related to a problem? Please describe.**
No HomePod support.

**Describe the solution you'd like**
By using the [Node Airtunes2 library](https://github.com/mcfisto/node_airtunes2) MP3 could be sent to the HomePods via Airplay.

**Describe alternatives you've considered**

**Additional context**

**Comment by luxi-asphericon** [comment]
That's a feature I miss too.
