### ISSUE TITLE
A lot of errors: "The document has moved"

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.sayit#139]
Since a couple of days I get a lot of errors in the log.
Using SayIt together with GoogleHome.

Using Node.js v14.17.0

`http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=T%C3%BCr.&tl=de&total=1&idx=0&textlen=4Cannot get file: <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8"><TITLE>302 Moved</TITLE></HEAD><BODY><H1>302 Moved</H1>The document has moved<A HREF="https://www.google.com/sorry/index?continue=https://translate.google.com/translate_tts%3Fie%3DUTF-8%26client%3Dtw-ob%26q%3DT%25C3%25BCr.%26tl%3Dde%26tob%3Dtrue&amp;q=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX">here</A>. </BODY></HTML>`

**Comment by Michaelnorge** [comment]
If I follow the link in the error message I see that:

Unsere Systeme haben ungewöhnlichen Datenverkehr aus Ihrem Computernetzwerk festgestellt. Bitte versuchen Sie es später erneut. Warum?

Diese Seite wird angezeigt, wenn Google automatisch Anfragen aus Ihrem Computernetzwerk erkennt, die anscheinend gegen die Nutzungsbedingungen verstoßen. Die Sperre läuft ab, sobald diese Anfragen eingestellt werden.

Dieser Datenverkehr wurde möglicherweise von bösartiger Software, einem Browser-Plug-in oder einem Skript gesendet, das automatische Anfragen verschickt. Falls Sie Ihre Netzwerkverbindung mit anderen teilen, bitten Sie Ihren Administrator um Hilfe. Möglicherweise ist ein anderer Computer, der dieselbe IP-Adresse verwendet, für die Anfragen verantwortlich. Weitere Informationen

Eventuell sehen Sie diese Seite, weil Sie komplexe Anfragen verwenden, die bekanntermaßen von Robots verwendet werden, oder weil Sie sehr schnell Anfragen senden.

**Comment by raintonr** [comment]
I'm noticing this too. Guess the adapter needs to trap and correctly handle these errors as here we get the output of the last successful speech render which might not always be the same as the one requested.

I have disabled this instance of sayit for now and turn it back on in couple of days to see if that is long enough between requests for Google to have cleared their 'unusual traffic' flag.

I do note that I can still visit the URL sayit generates directly in a browser on my laptop (same IP address from our LAN) and Google renders the text requested just fine, so maybe some adjustment of the request parameters could help?

**Comment by Xyolyp** [comment]
I would like to suggest an offline cache of a configurable size (e.g. last 100 distinct strings) to greatly reduce the amount of requests send to the tts engine for most users. This would not solve this issue directly but it would decrease the probability of the issue appearing in the first place.

**Comment by GermanBluefox** [comment]
please test in v1.12.3

**Comment by raintonr** [comment]
> please test in v1.12.3

OK - have installed that and will report any problems.
