### ISSUE TITLE
Sometimes no speech output

### ISSUE THREAD

**Issue by capitaenz** [ioBroker/ioBroker.sayit#140]
Hello,

sometimes sayit does not output.
I tried to say the time until the error came.
I have attached a log:

`
sayit.1	2021-05-23 17:54:33.401	debug	(5371) Duration "Es ist jetzt17:54": 0

sayit.1	2021-05-23 17:54:33.400	error	(5371) http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=Es%20ist%20jetzt17:54&tl=de&total=1&idx=0&textlen=17 Cannot get file: <HTML><HEAD><meta http-equiv="content-type" content="text

sayit.1	2021-05-23 17:54:32.556	debug	(5371) Cache File /opt/iobroker/cache/c0d7c1787d2dfd52527ccdd3a39b042d.mp3 for "de;Es ist jetzt17:54" not found

sayit.1	2021-05-23 17:54:32.554	info	(5371) saying: Es ist jetzt17:54

sayit.1	2021-05-23 17:54:31.551	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:54:31.514	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

sayit.1	2021-05-23 17:53:11.581	debug	(5371) Duration "Es ist jetzt17:53": 6

sayit.1	2021-05-23 17:53:11.559	info	(5371) Copied file "/opt/iobroker/iobroker-data/sayit/sayit.1.say.mp3" to "/opt/iobroker/cache/22fd47dfc6855e50d11ac4d21487cca6.mp3"

sayit.1	2021-05-23 17:53:11.555	debug	(5371) Caching File /opt/iobroker/cache/22fd47dfc6855e50d11ac4d21487cca6.mp3 for "de;Es ist jetzt17:53" now

sayit.1	2021-05-23 17:53:11.380	debug	(5371) Cache File /opt/iobroker/cache/22fd47dfc6855e50d11ac4d21487cca6.mp3 for "de;Es ist jetzt17:53" not found

sayit.1	2021-05-23 17:53:11.378	info	(5371) saying: Es ist jetzt17:53

sayit.1	2021-05-23 17:53:10.375	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:53:10.334	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

sayit.1	2021-05-23 17:52:04.220	debug	(5371) Duration "Es ist jetzt17:51": 6

sayit.1	2021-05-23 17:52:04.150	info	(5371) saying: Es ist jetzt17:51

sayit.1	2021-05-23 17:51:58.148	debug	(5371) Duration "Es ist jetzt17:51": 6

sayit.1	2021-05-23 17:51:58.117	info	(5371) saying: Es ist jetzt17:51

sayit.1	2021-05-23 17:51:52.114	debug	(5371) Duration "Es ist jetzt17:51": 6

sayit.1	2021-05-23 17:51:52.086	info	(5371) saying: Es ist jetzt17:51

sayit.1	2021-05-23 17:51:46.083	debug	(5371) Duration "Es ist jetzt17:51": 6

sayit.1	2021-05-23 17:51:46.056	info	(5371) saying: Es ist jetzt17:51

sayit.1	2021-05-23 17:51:45.054	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:51:45.020	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

sayit.1	2021-05-23 17:51:36.387	debug	(5371) Duration "Es ist jetzt17:51": 6

sayit.1	2021-05-23 17:51:36.329	info	(5371) Copied file "/opt/iobroker/iobroker-data/sayit/sayit.1.say.mp3" to "/opt/iobroker/cache/e4230a43dfc137042fbcf1ef352864d0.mp3"

sayit.1	2021-05-23 17:51:36.318	debug	(5371) Caching File /opt/iobroker/cache
/e4230a43dfc137042fbcf1ef352864d0.mp3 for "de;Es ist jetzt17:51" now

sayit.1	2021-05-23 17:51:36.110	debug	(5371) Cache File /opt/iobroker/cache/e4230a43dfc137042fbcf1ef352864d0.mp3 for "de;Es ist jetzt17:51" not found

sayit.1	2021-05-23 17:51:36.107	info	(5371) saying: Es ist jetzt17:51

sayit.1	2021-05-23 17:51:35.105	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:51:35.070	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3
sayit.1	2021-05-23 17:50:32.007	debug	(5371) Duration "Es ist jetzt17:50": 5

sayit.1	2021-05-23 17:50:31.967	info	(5371) saying: Es ist jetzt17:50

sayit.1	2021-05-23 17:50:30.964	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:50:30.926	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

sayit.1	2021-05-23 17:50:01.906	debug	(5371) Duration "Es ist jetzt17:50": 5

sayit.1	2021-05-23 17:50:01.870	info	(5371) Copied file "/opt/iobroker/iobroker-data/sayit/sayit.1.say.mp3" to "/opt/iobroker/cache/749a46a2809702f68267bc4a8bd4fb59.mp3"

sayit.1	2021-05-23 17:50:01.864	debug	(5371) Caching File /opt/iobroker/cache/749a46a2809702f68267bc4a8bd4fb59.mp3 for "de;Es ist jetzt17:50" now

sayit.1	2021-05-23 17:50:01.557	debug	(5371) Cache File /opt/iobroker/cache/749a46a2809702f68267bc4a8bd4fb59.mp3 for "de;Es ist jetzt17:50" not found

sayit.1	2021-05-23 17:50:01.555	info	(5371) saying: Es ist jetzt17:50

sayit.1	2021-05-23 17:50:00.552	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:50:00.506	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

sayit.1	2021-05-23 17:48:23.926	debug	(5371) Duration "Es ist jetzt17:48": 6

sayit.1	2021-05-23 17:48:23.882	info	(5371) saying: Es ist jetzt17:48

sayit.1	2021-05-23 17:48:22.879	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:48:22.836	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

sayit.1	2021-05-23 17:47:25.840	debug	(5371) Duration "Es ist jetzt17:47": 6

sayit.1	2021-05-23 17:47:25.806	info	(5371) saying: Es ist jetzt17:47

sayit.1	2021-05-23 17:47:24.803	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:47:24.756	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

sayit.1	2021-05-23 17:47:04.878	debug	(5371) Duration "Es ist jetzt17:47": 6

sayit.1	2021-05-23 17:47:04.695	info	(5371) saying: Es ist jetzt17:47

sayit.1	2021-05-23 17:47:03.692	debug	(5371) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1

sayit.1	2021-05-23 17:47:03.488	info	(5371) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

sayit.1	2021-05-23 17:47:01.370	debug	(5371) system.adapter.admin.0: logging true

`

**The output runs on ioBroker slave (PI3)
raspi-vis-keller**

Betriebssystem linux
Architektur arm
CPUs 4
Geschwindigkeit 700 MHz
Modell ARMv7 Processor rev 4 (v7l)
RAM 975.39 MB
System Betriebszeit 13 T. 04:40:05
Node.js v12.21.0 (Es gibt eine neuere Version: v12.22.1)
NPM 6.14.11
Festplatte Größe 28.99 GB
Festplatte frei 25.01 GB
Anzahl der Adapter 341
Betriebszeit13 T. 04:44:06
Aktive Instanzen 3
Hostname raspi-vis-keller

**ioBroker main:
debian-iobroker**

Betriebssystem linux
Architektur x64
CPUs 4
Geschwindigkeit 1098 MHz
Modell Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM 7.68 GB
System Betriebszeit 288 T. 06:40:32
Node.js v12.21.0 (Es gibt eine neuere Version: v12.22.1)
NPM 6.14.11
Festplatte Größe 90.11 GB
Festplatte frei 83.44 GB
Anzahl der Adapter 341
Betriebszeit 84 T. 23:03:30
Aktive Instanzen 31
Hostname debian-iobroker

sayit version: 1.12.2
Player: mpg321
Language: Google - Deutsch

Where do I look for the error?
Greetings
Leif

**Comment by GermanBluefox** [comment]
Google API was changed. Can you retest with 1.12.3
