### ISSUE TITLE
Problem with Google speach API

### ISSUE THREAD

**Issue by uklatt** [ioBroker/ioBroker.sayit#145]
Something must have changed with Google speach API.
Its not possible to download the MP3 file with ioBroker.sayit anymore.
ioBroker shows only an error message:
![Bild1](https://user-images.githubusercontent.com/42005666/121414529-05bcb600-c967-11eb-87c2-35bdcec3a49d.png)

When I use the same URL in the browser, it works like a charm...

Uwe

**Comment by beabel** [comment]
I have the same problem.
Please can someone update this adapter?

**Comment by texiuozelotl** [comment]
Same Problem here...

**Comment by capitaenz** [comment]
Same Problem here:
[https://github.com/ioBroker/ioBroker.sayit/issues/140](https://github.com/ioBroker/ioBroker.sayit/issues/140)
I'm switching to AWS Polly, no problems with that.

**Comment by technicallife** [comment]
same here :-(

**Comment by DragonDope** [comment]
I have the same problem.

**Comment by baeriwiliwonka** [comment]
Any solution in the pipeline?

**Comment by GermanBluefox** [comment]
please test in v1.12.3

**Comment by uklatt** [comment]
Funktioniert wieder mit Google!
Danke GermanBluefox.
Uwe
