### ISSUE TITLE
AWS Neural Voice Support 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.sayit#146]
Hallo, 

Ich würde mich sehr freuen, wenn die "AWS Neural Voice" unterstützt würde.
Diese klingt wirklich sehr gut. 

Näheres findet man unter
[https://docs.aws.amazon.com/polly/latest/dg/NTTS-main.html](https://docs.aws.amazon.com/polly/latest/dg/NTTS-main.html) 

Ich habe leider sehr wenig Ahnung von dem Thema.
Wie es scheint, muss bei der Anfrage "nur" eine andere Engine ausgewählt werden. 

```
The engine parameter is optional, with two possible values: standard or Neural. Use this property when creating a SynthesisSynthesisTask operation.

For example, you can use the following code to run the start-speech-synthesis-task AWS CLI command in the US West-2 (Oregon) region

The following AWS CLI example is formatted for Unix, Linux, and macOS. For Windows, replace the backslash (\) Unix continuation character at the end of each line with a caret (^) and use full quotation marks (") around the input text with single quotes (') for interior tags.


aws polly start-speech-synthesis-task \
  --engine neural
  --region us-west-2 \
  --endpoint-url "https://polly.us-west-1.amazonaws.com/" \
  --output-format mp3 \
  --output-s3-bucket-name your-bucket-name \
  --output-s3-key-prefix optional/prefix/path/file \
  --voice-id Joanna \
  --text file://text_file.txt
```

**Comment by GermanBluefox** [comment]
Vicki added in v1.12.3

**Comment by ipod86** [comment]
Cool, danke.
Vicky konnte man vorher ja auch schon auswählen. 
Gibt es für natural Voice einen Parameter den man mitgeben muss? 
In der Liste mit den Stimmen finde ich es nicht explizit.

**Comment by GermanBluefox** [comment]
Nein. Man kann nichts einstellen:
![image](https://user-images.githubusercontent.com/4582016/123507842-0db96d00-d66c-11eb-833b-b3fc9f6dfcd7.png)

**Comment by ipod86** [comment]
Also ist Vicky ab jetzt immer Neural?
Da wäre ein Hinweis im Adapter ja gut, da Neural mehr kostet.
