### ISSUE TITLE
Timeout/Pause/Volume Blockly problems

### ISSUE THREAD

**Issue by maxpd1** [ioBroker/ioBroker.sayit#147]
Hi,

when you have 2 or more outputs with a pause inbetween set up via a blockly timeout or pause I face several bugs.
Sometimes outputs are stopped other outputs are spoken twice and the outputs have different volumes.

Is it possible to integrate the options you have via JS into blockly?

I especially speak about speach output speed and the pause options to make the output with a pause more natural.

Because if you have only one sayit output there is no problem with volume and cut off speaches as well as duplicates.

Regards maxpd

**Comment by GermanBluefox** [comment]
ioBroker cannot control speed of text

**Comment by maxpd1** [comment]
That's a pity, but ok. How about a pause?
