### ISSUE TITLE
No cloud voices since update 

### ISSUE THREAD

**Issue by meistermopper** [ioBroker/ioBroker.sayit#159]
Since update to admin 5.1.23 and cloud 4.1.0 the cloud voices (e.g. cloud deutsch) in sayIt (1.12.3) could not be used any longer, google german works.

In log there is:
`sayit.0 | 2021-08-11 15:10:12.191 | error | No app key found in "cloud.0".`

Actually there is a pro-key in cloud.0 inserted.

Best regards

Thomas

**Comment by bahnuhr** [comment]
Ich habe das gleiche Problem.
Wäre gut, wenn dies wieder laufen würde.

**Comment by bahnuhr** [comment]
Aber gerne nochmal Zusammenfassung:
Wenn man in sayit wählt: cloud-deutsch-marlene
dann war Voraussetzung, dass man Adapter cloud installiert hat und dort seine Zugangsdaten eingegeben hat.
Wie in der doku sayit beschrieben konnte der Cloud Adapter dann auch deaktiviert sein.
Der Cloud Adapter hat dann irgendwie mit AWS kommuniziert und die mp3 bekommen die dann abgespielt wurde.
Und dies funktioniert nicht mehr.
Es kommt im log: sayit.0 | 2021-08-11 15:10:12.191 | error | No app key found in "cloud.0".
Dies würde aber eher für einen Adapter (welcher auch immer) Problem sprechen.

**Comment by Jey-Cee** [comment]
Ich hab das Problem gefunden. Der APP Key kann nicht mehr aus der Cloud Konfiguration gelesen werde.
Das scheint ein neuer Sicherheitsmechanismus zu sein der das auslesen von Kritischen Daten verhindern soll.

Ich Arbeite gerade an dem Adapter und habe einen Workaround dafür eingebaut. 
Bis die Version zur Verfügung steht wird noch eine Weile dauern, da auch der Admin ein Update braucht damit die Version dann läuft.

**Comment by bahnuhr** [comment]
Danke für die Info @Jey-Cee 
Wenn es zeitnah gehen würde, wäre dies toll.

Wenn es noch Monate dauert, wäre dies nicht so schön.

Aber nochmal Danke fürs Kümmern.

**Comment by bahnuhr** [comment]
Hallo @Jey-Cee 
Auch hier, kannst du sagen wann dies voraussichtlich kommen wird.
mfg

**Comment by Jey-Cee** [comment]
Swlbe Antwort.

**Comment by philbamberg** [comment]
Wie siehts denn aus? Ist ja jetzt schon ein Monat vergangen und das Problem liegt noch vor. N kurzer Input wäre super :-)

**Comment by Jey-Cee** [comment]
Bei dem PR mit den Änderungen gab es einige Änderungswünsche. Momentan bin ich nicht in der Lage sie um zu setzen. Somit wird es noch ne weile dauern.

**Comment by bahnuhr** [comment]
@Jey-Cee 
Hallo,
gibt es schon Licht am Ende des Tunnels.
Oder konkret:
Wann kann man voraussichtlich mit einer Aktivierung der alten Stimmen rechnen ?
Oder wird es dies nicht mehr geben.
Dann sollte man den Adapter ändern.
mfg
Dieter

**Comment by bahnuhr** [comment]
Konntest du schmal nachprüfen.

Bitte kurze Rückinfo.

danke.

mfg
Dieter

**Comment by Jey-Cee** [comment]
Nein hab ich mir noch nicht angeschaut, aber das Zeichen Limit gibt es nicht mehr.
Aber das mit dem No app key found gab es auch vorher schon. 
Das hatte was mit den neuen Sicherheitsfeatures in ioBroker zu tun.
Interessant ist das es nur bei längeren Texten Auftritt.

**Comment by bahnuhr** [comment]
Könntest du dir dies nochmal anschauen.
Wenn ich irgendwie helfen kann, sag Bescheid.
Danke.

**Comment by Jey-Cee** [comment]
> Könntest du dir dies nochmal anschauen. Wenn ich irgendwie helfen kann, sag Bescheid. Danke.

So ich hab mir das jetzt mal angeschaut. Ich bin davon Überzeugt das die Version von mir gar nicht installiert wurde. 
Welche Admin Version hast du Installiert?

**Comment by bahnuhr** [comment]
Ich habe eigentlich o.g. Link:
https://github.com/Jey-Cee/ioBroker.sayit
über die Katze manuell installiert (wie immer bei manuellen Installationen).
Zusätzlich dann rechts noch upload gedrückt.

Hat sich die Vorgehensweise da irgendwie geändert?

admin: 5.1.25
node.js: 14.18.1
npm: 6.14.15
host: 3.3.20

Fazit: ich probiere es nochmal.

**Comment by Jey-Cee** [comment]
Deine Admin Version ist zu niedrig. Du brauchst min 5.1.28 sonst lässt sich der Adapter gar nicht installieren.

**Comment by bahnuhr** [comment]
Und wie komme ich an die admin 5.1.28.
Selbst im beta wird mir nur die 5.1.25 angeboten.
Muss ich über die Katze installieren?
Oder manuell per npm install ...

**Comment by Jey-Cee** [comment]
Über die Beta wird mittlerweile sogar die 5.2.1 verteilt.
Wenn das wirklich nicht angezeigt wird musst du es über die Katze installieren, aber von npm.

**Comment by bahnuhr** [comment]
das ist aber komisch
bei mir steht im stable: 5.1.25
und im beta: 5.1.21 ???

strg+f5 hab ich gedrückt.

Ich probier es heute Abend noch.
mfg
Dieter

**Comment by bahnuhr** [comment]
so habe alles installiert bekommen.
Aber das hört sich noch schlimmer an als vorher.
marlene ist auch nicht mehr auswählbar.
Und tts hab ich auch nicht mehr gefunden.

Schade.
Aber so ist es viel schlechter geworden.
oder ich habe die Einstellungen übersehen.

**Comment by bahnuhr** [comment]
Außerdem stürzt sayit nun ab.
`<html>
<body>


host.VM-iobroker | 2021-12-01 18:40:34.152 | error | instance system.adapter.sayit.4 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.VM-iobroker | 2021-12-01 18:40:34.152 | error | Caught by controller[1]: at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:183:89)
host.VM-iobroker | 2021-12-01 18:40:34.152 | error | Caught by controller[1]: TypeError: Cannot read property 'common' of null
host.VM-iobroker | 2021-12-01 18:40:34.151 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
sayit.4 | 2021-12-01 18:40:33.550 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
sayit.4 | 2021-12-01 18:40:33.548 | info | terminating
sayit.4 | 2021-12-01 18:40:33.047 | info | stopping...
sayit.4 | 2021-12-01 18:40:33.034 | error | Cannot read property 'common' of null
sayit.4 | 2021-12-01 18:40:33.033 | error | TypeError: Cannot read property 'common' of null at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:183:89)
sayit.4 | 2021-12-01 18:40:33.029 | error | unhandled promise rejection: Cannot read property 'common' of null
sayit.4 | 2021-12-01 18:40:33.028 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>`

**Comment by bahnuhr** [comment]
Hallo Christoph,
ich muss nochmal nachfragen.
Ist es zukünftig angedacht, dass "Marlene" und/oder TTS nicht mehr geht.
Wäre sehr schade; und würde den WAF massiv nach unten ziehen.
Bekomme ja jetzt schon täglich gesagt, wie schlecht die TTS Stimme ist (im Gegensatz zu vorher "Marlene").

mfg
Dieter

**Comment by Jey-Cee** [comment]
Das es bei dir jetzt gar nicht mehr funktioniert ist natürlich ärgerlich. Marlene direkt über AWS funktioniert also Nein es ist nicht geplant sie zu entfernen. 
Ich hatte jetzt nicht explizit nochmal über die Cloud getestet, entfernt hab ich sie hier auch nicht.

> Und tts hab ich auch nicht mehr gefunden.

Was meinst du damit?

**Comment by bahnuhr** [comment]
In der alten Version gebe ich "browser" ein.
Dann kommt rechts Sprache.
und dort konnte man eingeben, z.B.
- PicoTTS-Deutsch
- Cloud-Deutsch-Marlene
Bei Auswahl "Marlene" muss man dann noch unten die Cloud eingeben, bei mir: cloud.0

Und dies alles finde ich in der neuen Ansicht nicht.
Also weder "Marlene" und auch nicht "PicoTTS"

Diese Auswahl ist einfach nicht mehr vorhanden. Über ich bin blind ;-)

**Comment by Jey-Cee** [comment]
Ich glaub du bist blind. ;-)
 Wechsel mal den Tab, keine Ahnung warum man immer auf dem zweiten Tab landet.

**Comment by bahnuhr** [comment]
Ich hab eigentlich jeden Tap durchgeklickt.
Nicht gefunden.
Also, ich probiers nochmal.
mfg
Dieter

**Comment by Jey-Cee** [comment]
So sieht das bei mir aus:

**Comment by bahnuhr** [comment]
So, alles neu installiert.
Und jetzt hab ich auch gefunden (war wohl gestern doch blind).
Aber im log kam beim Start dies:
`<html>
<body>


host.VM-iobroker | 2021-12-02 19:29:19.662 | error | instance system.adapter.sayit.4 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.VM-iobroker | 2021-12-02 19:29:19.662 | error | Caught by controller[1]: at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:183:89)
host.VM-iobroker | 2021-12-02 19:29:19.661 | error | Caught by controller[1]: TypeError: Cannot read property 'common' of null
host.VM-iobroker | 2021-12-02 19:29:19.657 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
sayit.4 | 2021-12-02 19:29:19.051 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
sayit.4 | 2021-12-02 19:29:19.049 | info | terminating
sayit.4 | 2021-12-02 19:29:18.548 | info | stopping...
sayit.4 | 2021-12-02 19:29:18.533 | error | Cannot read property 'common' of null
sayit.4 | 2021-12-02 19:29:18.533 | error | TypeError: Cannot read property 'common' of null at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:183:89)
sayit.4 | 2021-12-02 19:29:18.528 | error | unhandled promise rejection: Cannot read property 'common' of null
sayit.4 | 2021-12-02 19:29:18.527 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>`

**Comment by bahnuhr** [comment]
Die Sprache scheint aber zu funktionieren.
Danke.

**Comment by bahnuhr** [comment]
![image](https://user-images.githubusercontent.com/25694404/144564591-f95a585c-81dd-4cf4-94f1-416e1367949e.png)

**Comment by bahnuhr** [comment]
eben ca. 10 min. probiert. Es kam gar kein Pfeil mehr.

**Comment by Jey-Cee** [comment]
Wenn die Auswahl nicht funktioniert läuft der Adapter nicht. Die Daten in der Auswahl kommen vom Adapter.

**Comment by bahnuhr** [comment]
ja, ist wohl so. Adapter war rot.
Also Neustart; Adapter ist grün.
Und die Auswahl war wieder da.
(muss man aber auch erstmal drauf kommen ;-) )

**Comment by bahnuhr** [comment]
Und eben wieder diesen catch Fehler.
`<html>
<body>


ost.VM-iobroker | 2021-12-03 08:51:09.722 | error | instance system.adapter.sayit.4 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.VM-iobroker | 2021-12-03 08:51:09.721 | error | Caught by controller[1]: at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:183:89)
host.VM-iobroker | 2021-12-03 08:51:09.721 | error | Caught by controller[1]: TypeError: Cannot read property 'common' of null
host.VM-iobroker | 2021-12-03 08:51:09.716 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
sayit.4 | 2021-12-03 08:51:09.091 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
sayit.4 | 2021-12-03 08:51:09.089 | info | terminating
javascript.0 | 2021-12-03 08:51:08.621 | info | script.js.Scripte.Geraete.Waschmaschine: Auslöser Waschmaschine
sayit.4 | 2021-12-03 08:51:08.588 | info | stopping...
sayit.4 | 2021-12-03 08:51:08.573 | error | Cannot read property 'common' of null
sayit.4 | 2021-12-03 08:51:08.572 | error | TypeError: Cannot read property 'common' of null at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:183:89)
sayit.4 | 2021-12-03 08:51:08.568 | error | unhandled promise rejection: Cannot read property 'common' of null
sayit.4 | 2021-12-03 08:51:08.567 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>`

Konntest du da schon was finden ?

**Comment by bahnuhr** [comment]
![image](https://user-images.githubusercontent.com/25694404/144578344-45ada1cb-050c-4aaa-b646-ac5d84c8b685.png)

Und diese Meldung kommt dann auch.

**Comment by mrbjoernson** [comment]
Hallo zusammen, ich verfolge das Thema nun auch schon eine Weile und hatte heute mal Zeit zum Testen. 
Bei mir ist es so, dass egal welche Cloud und Stimme ich wähle, immer die gelangweilte Google Stimme genutzt wird. Das ist natürlich besser als nichts. Das einzige was hier noch stört, die Lautstärke wird nicht als solche erkannt. Dieser Wert wird zu Beginn mit vorgelesen und die Lautstärke startet immer mit 70%.

**Comment by bahnuhr** [comment]
Das mit der Lautstärke hat bei mir noch nie geklappt. Ich steuere diese so, dass ich die Lautstärke des Tablet per Script einstelle.

**Comment by Erbse69** [comment]
Hallo zusammen!

Ich erlaube mir auch mal, hier einzusteigen, da ich auch seit August das Thema verfolge. Ich habe den Adapter (1.12.3) und auch den Chromecast Adapter (2.3.1) gestern nochmal komplett neu installiert. 

Ich nutze sayit über diverse Google Home und Google Home Mini zur Ausgabe von Meldungstexten. Die Lautstärkeregelung funktioniert bei mir, der Google Home schaltet auf die angegebene Lautstärke und nach der Wiedergabe zurück auf die vorher eingestellte Lautstärke. 

Was seit ca. August nicht mehr funktioniert, ist die Ausgabe über die Cloud (Hans, Marlene, etc.). Wenn ich diese einstelle, bleibt der Google Home stumm und im Log erscheint die Fehlermeldung `No app key found in "cloud.0".` Dort ist aber Pro-App-Key eingetragen.

Etwas erstaunt bin ich über den screenshot in [https://github.com/ioBroker/ioBroker.sayit/issues/159#issuecomment-985286592](url)
Bei mir fehlen die Register VOICE | OUTPUT | ANNOUNCEMENT, das ist bei mir alles auf einer Seite. Das aber nur nebenbei.

Was mir auch nicht ganz klar ist, ist der Unterschied zwischen Ausgabe auf Chromecast und Google Home. Es funktionieren beide mit der Standardsprache. Die Fehlermeldung `No app key found in "cloud.0".` erscheint auch bei beiden bei Auswahl einer Cloud-Sprache. 

Bei Ausgabe auf Chromecast konnte ich früher noch auf Gruppen zugreifen, die in der Google Home App eingerichtet sind (Alle, Dachgeschoss, etc.). Jetzt klappt das leider auch nicht mehr, im Log erscheint dann die Fehlermeldung: `Dachgeschoss - Could not play announcement: TypeError: Cannot read property 'launch' of null`

Gerne helfe ich mit, hier weiter zu kommen. Wenn ich etwas testen soll oder noch Infos benötigt werden - einfach Bescheid geben.

**Comment by bahnuhr** [comment]
Hallo Christoph,
es funktioniert doch nicht.
Bei Abspielen eines schon gechachten Textes funktioniert es, z.B.
`<html>
<body>


sayit.4 | 2021-12-05 07:39:00.586 | info | saying: Spülmaschine ist fertig. 
-- | -- | -- | --



</body>
</html>`
Der Text wird gesprochen.

Bei dem Versuch eines neuen Textes, z.B. Spülmaschine ist fertig. 1 2 3
kommt der o.g. "no app key found in "undefined"

Fazit:
Es funktioniert noch nicht.
Anmerkung:
Früher musste man bei "marlene" auch noch die cloud.0 angeben; was nun nicht mehr möglich ist.

**Comment by bahnuhr** [comment]
So,
nun noch ne Rückinfo von mir:
Es klappt doch. (Error 50 = Das Problem war 50 cm vor dem Bildschirm)
Man muss natürlich auch die iob api key eingeben. Dann klappt es auch mit neuen Texten.

Fazit:
Bei mir klappt nun "Marlene". Bei gechachten und auch bei neuen Texten.

**Comment by bahnuhr** [comment]
> Etwas erstaunt bin ich über den screenshot in [https://github.com/ioBroker/ioBroker.sayit/issues/159#issuecomment-985286592](url)
> Bei mir fehlen die Register VOICE | OUTPUT | ANNOUNCEMENT, das ist bei mir alles auf einer Seite. Das aber nur nebenbei.

Das hatte sich geändert nach manueller Installation der Version von Christoph:
https://github.com/Jey-Cee/ioBroker.sayit

**Comment by bahnuhr** [comment]
Christoph,
noch ne Frage.

Wenn man einen Text "Spülmaschine ist fertig." schon ewig erzeugt hat, dann wird dieser ja gespeichert. Und dies erfolgt auch mit der alten, damals eingestellten Stimme (z.B. picotts).
Wenn man dann die Stimme ändert, z.B. auf "marlene" und den gleichen Text wieder abspielt, wird ja kein neues mp3 erzeugt (weil ja schon irgendwo gespeichert).
Es wird dann immer noch die alte Datei (mit der alten Stimme) abgespielt.

Frage:
Kann/muss man die alten cache Dateien löschen. Und wenn ja, wo ?

**Comment by bahnuhr** [comment]
> Kann/muss man die alten cache Dateien löschen. Und wenn ja, wo ?

Habe alle mp3 (617 Dateien) in /opt/iobroker/cache/ gelöscht.
Scheint geklappt zu haben.

**Comment by Erbse69** [comment]
> Das hatte sich geändert nach manueller Installation der Version von Christoph: https://github.com/Jey-Cee/ioBroker.sayit

Ich meinte, das schon gemacht zu haben, war aber da wohl nicht über Benutzerdefiniert und die URL gegangen. Die Sprachausgabe über die Cloud funktioniert jetzt wieder! Vielen Dank! 

Allerdings habe ich jetzt auch den Bug, dass die Lautstärke vorgelesen wird:

![image](https://user-images.githubusercontent.com/65916777/144745817-792c0312-6c48-432d-9f33-a9f9eba821dd.png)

Sprachausgabe: **"siebzigster Test"**

Eine Kleinigkeit, die man ggf. noch anpassen könnte: Im Cloud Adapter heißt es **APP**-KEY, hier im Adapter "Cloud **API** Key".

**Comment by Erbse69** [comment]
Zum Thema Lautstärke habe ich folgendes probiert, leider ohne Erfolg:
```
setState("sayit.1.tts.volume", 50);
setState("sayit.1.tts.text", "Test");
```
Der Wert 50 landet zwar im Objekt Volume, wird aber leider ignoriert.

**Comment by Jey-Cee** [comment]
Heute Abend mach ich im Forum ein Thema zu meiner Version auf, dann können wir dort weiter Diskutieren und alles Sammeln. Bitte hier nichts weiter dazu schreiben.

**Comment by Erbse69** [comment]
Prima, vielen Dank! Bitte hier dann noch den Link posten.

**Comment by mrbjoernson** [comment]
@Jey-Cee könntest du bitte den Link zum Beitrag im Forum posten. Ich kann den Beitrag dort leider nicht finden. Vielen Dank :)

**Comment by Jey-Cee** [comment]
Hier ist der Link: https://forum.iobroker.net/topic/50036/test-adapter-chromecast-v3-0-x

**Comment by bahnuhr** [comment]
Der Link ist Chromecast.

Wolltest du nicht etwas bzgl. Sayit einstellen..

Mfg
Dieter

**Comment by Jey-Cee** [comment]
Ja wollte ich, ist wohl untergegangen. Muss mich erst mal auskurieren, damit ich wieder Klar bin im Kopf.

**Comment by Erbse69** [comment]
Hallo Christoph,
ich hoffe, es geht Dir wieder besser und wünsche Dir ein frohes neues Jahr! 

Hattest du zwischen den Jahren evtl. etwas Zeit nach dem Thema Lautstärkeeinstellung zu schauen? 
[Link 1](https://github.com/ioBroker/ioBroker.sayit/issues/159#issuecomment-985904576)
[Link 2](https://github.com/ioBroker/ioBroker.sayit/issues/159#issuecomment-986218824)
[Link 3](https://github.com/ioBroker/ioBroker.sayit/issues/159#issuecomment-986221909)

Gruß,
Stefan

**Comment by mrbjoernson** [comment]
@Erbse69 ich habe jetzt für den Übergang ein Blockly Script erstellt, welches während einer Audioausgabe die Lautstärke überwacht und entsprechend runter regelt, wenn zu laut. Ist jetzt nicht der schönste Weg, aber zur Überbrückung besser als nichts. Eventuell ließe sich da über Javascript auch was schöneres bauen.

**Comment by Erbse69** [comment]
> ich habe jetzt für den Übergang ein Blockly Script erstellt,

@mrbjoernson Könntest Du das Script bitte hier zur Verfügung stellen?

**Comment by fir3drag0n** [comment]
> @Erbse69 ich habe jetzt für den Übergang ein Blockly Script erstellt, welches während einer Audioausgabe die Lautstärke überwacht und entsprechend runter regelt, wenn zu laut. Ist jetzt nicht der schönste Weg, aber zur Überbrückung besser als nichts. Eventuell ließe sich da über Javascript auch was schöneres bauen.

an dem Blockly wäre ich auch interessiert.

**Comment by mrbjoernson** [comment]
Sorry, ich habe es leider nicht früher geschafft. Wie bereits erwähnt ist das Blockly wirklich nur eine Notlösung. Vielleicht auch nicht ganz sauber umgesetzt. Aber für mich ist es auf jeden Fall besser als vom Lautsprecher angeschrieben zu werden oder komplett auf Durchsagen zu verzichten.

Kurz zu meinem Setup. Ich habe diverse Google Lautsprecher, welche ich über die Chromcast Erweiterung in iobroker eingebunden habe. 

Das folgende Beispiel bezieht sich auf den Lautsprecher im Bad.

Es gibt insgesamt zwei Trigger. 

### **Erster Trigger-Block**:
**TRIGGER OBJEKT**
Hier hat sich die Variable ***.status.text*** angeboten, da sich diese sowohl zu Beginn als auch zum Ende eine Durchsage ändert.

**FALLS**
Hier soll zunächst erkannt werden, ob gerade eine Durchsage von Sayit läuft. Nur damit das Script nicht aktiv wird, wenn z. B. über Spotify Musik wiedergegeben wird. Bei mir steht in der Variablen ****.status.displayName*** immer ***Default Media Receiver*** bei Sayit Durchsagen. Daher gibt es zunächst eine entsprechende Abfrage ob dort dieser Text momentan aktiv ist.

In die Variable ***Bad_aktiv*** soll der Status geschrieben werden, ob gerade eine Durchsage über Sayit aktiv ist oder nicht. Da dies zu beginn nicht der Fall ist, muss diese Variable ungleich wahr sein. 

**MACHE**
Als nächstes wird die Variable ***Bad_aktiv*** auf wahr gesetzt und kurz danach schon mal die Lautstärke auf das gewünschte Level eingestellt. Da sich die Lautstärke meistens aber noch mal erhöht, muss man entsprechend noch mehrmals Gegensteuern und diese wieder senken. Das passiert dann im zweiten Trigger Block. 

**SONST FALLS**
Hier geht es darum abzufragen ob die Durchsage vorbei ist. Dafür eignet sich die Variable ****.status.text***. Währende der Durchsage steht hier eine URL drin. Danach steht dort ebenfalls der Text ***Defaul Media Recevier***. Die Variable ***Bad_aktiv*** sollte jetzt noch wahr sein. Wenn beide Voraussetzungen entsprechend erfüllt sind, ist die Durchsage zu Ende.

**MACHE**
Deshalb wird die Variable ***Bad_aktiv*** nun wieder auf falsch gesetzt und der Lautsprecher bekommt die Lautstärke zugewiesen, die er vor der Durchsage hatte. Die ursprüngliche Lautstärke wird im zweiten Trigger-Block gesetzt.


### **Zweiter Trigger-Block**:
**TRIGGER OBJEKT**
Hier geht es darum die Lautstärke zu überwachen, weshalb ich mich für die Variable ***.status.volume*** entschieden habe.

**FALLS**
Hier fragen wir ab ob gerade eine Durchsage läuft mit der Variablen ***Bad_aktiv*** und ob das Level der Lautstärke zu hoch ist. Da ich mich für 35 entschieden hatte, prüfen wir ob die Lautstärke nun höher ist als 35 oder nicht.

**MACHE**
Sollte die Lautstärke über 35 sein, wird sie wieder auf 35 gesetzt.

**SONST**
Dieser Teil schreibt die ursprüngliche Lautstärke in eine Variable, damit wir nach einer Durchsage die Lautsprecher wieder auf die Ausgangslautstärke stellen können. 


Ich hoffe der Blockly hilft euch weiter. Bei Fragen und Verbesserungsideen meldet euch gern.  

<a href="https://ibb.co/C1tqwZC"><img src="https://i.ibb.co/LkPM0Wj/Bildschirmfoto-2022-01-25-um-13-10-37.png" alt="Bildschirmfoto-2022-01-25-um-13-10-37" border="0"></a>

**Comment by mwp007** [comment]
jetzt mal so ganz blöd gefragt. Wäre es nicht am einfachsten einfach ein textfeld für den API Key in der Adapter Konfiguration zu platzeieren und es ohne Umwege über den Cloud Adapter direkt aus den Optionen zu holen ?

**Comment by GermanBluefox** [comment]
> jetzt mal so ganz blöd gefragt. Wäre es nicht am einfachsten einfach ein textfeld für den API Key in der Adapter Konfiguration zu platzeieren und es ohne Umwege über den Cloud Adapter direkt aus den Optionen zu holen ? Ich hab den Cloud Adapter eh nur um dortden Api key zu hinterlegen. Ansosnten ist er deaktiviert.

Implemented in 3.0.3
