### ISSUE TITLE
BUG: Längere Texte gehen nicht mehr !

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sayit#160]
Instanz sayit: google-deutsch

Wie oben schon beschrieben funktioniert die Ansage nicht mehr bei längeren Texten

Dieser Text funktioniert: ...setState('sayit.4.tts.text','Manueller Mähauftrag: Start: sofort, Ende: 14:00');

Dieser funktioniert nicht mehr: ...setState('sayit.4.tts.text','Manueller Mähauftrag: Start: sofort, Ende: 14:00, Danach: Auto wird ausgeführt');

Es kommt im log:  ...Cannot get file:TypeError: text should be a string

vgl. Thread: https://forum.iobroker.net/topic/46996/sayit-anzahl-zeichen-wurden-reduziert/7

**Comment by Jey-Cee** [comment]
Problem ist mit der nächsten Version gelöst.

**Comment by bahnuhr** [comment]
Auch hier Danke für Kümmern.

mfg
Dieter

**Comment by bahnuhr** [comment]
@Jey-Cee 
Hallo,
kannst du mir sagen, wann die nächste version voraussichtlich kommen wird.
mfg

**Comment by Jey-Cee** [comment]
Nein, da ich nicht weis wann die Änderungen im Admin überbommen werden.

**Comment by kptkip** [comment]
Gibt es schon ein Update zu dem Längen-Problem?
Ist das nur bei Google-DE so oder bei allen Services?
VG

**Comment by bahnuhr** [comment]
@kptkip 
probier mal die:
https://github.com/Jey-Cee/ioBroker.sayit
