### ISSUE TITLE
Fileupload funktioniert nicht

### ISSUE THREAD

**Issue by Choqui22** [ioBroker/ioBroker.sayit#193]
Ich versuche verzweifelt eine eigene Datei im Adapter hochzuladen (kleine .mp3).
Der Balken unter der Auswahl wird auch grün aber das wars. Anschließend ist immer noch nur gong und scifi auszuwählen.

was mache ich falsch? Besten Dank

**Comment by GermanBluefox** [comment]
Please retest with 2.x
