### ISSUE TITLE
Sound notification

### ISSUE THREAD

**Issue by vtec83** [ioBroker/ioBroker.sayit#2]
Next installed driver there is no Sound Notification

![sayit1](https://cloud.githubusercontent.com/assets/12570996/9153730/8f8f0b36-3e84-11e5-82ef-21167686c9d0.png)
![sayit2](https://cloud.githubusercontent.com/assets/12570996/9153735/94fc5808-3e84-11e5-87b9-3fc41a0213d6.png)

**Comment by vtec83** [comment]
After the restart, sound notifications by default is displayed.

**Comment by vtec83** [comment]
But in my downloaded sayit.0, no.Need more time to load in sayit.1

**Comment by GermanBluefox** [comment]
Adapter will be started by default. And announce selection will be available immediately.
