### ISSUE TITLE
Wrong pronounciation

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.sayit#20]
I switched Sayit to AWS Polly Marlene and have issues when it tries to say numbers like temperatures and humidities.
Example:

- "es ist 1.2 °C" will be pronounced as "Es ist erste zwei Grad Celsius" 
That is simply wrong and nobody understands that. I should be "Es ist eins komma 2 Grad Celsius" or at least "Es ist eins punkt zwei Grad Celsius"
- "es ist 3.14 °C" will be pronounced as "es ist dritte vierzehn Grad Celsius", which is wrong as well.
- It is getting worse when it tries to say "es ist 3.141 °C". This will result in "Es ist dreitausend einhundert einundvierzig Grad Celsius", which is completely BS.
- It is not getting better with more digits: "es ist 3.1415 °C" results in "es ist dritter eintausend vierhundert fünfzehn Grad Celsius" 

That is completely unusable.

Ralf

**Comment by Apollon77** [comment]
is it possible that with a german language it awaits a comma as decimal separator? Do you ever tried 1,2 instead of 1.2?

**Comment by derrapf** [comment]
Even if I would try it and it would work: It would probably not help me, becaues the home automation sensors return values in decimal notation, which are passed to the sayit adaptor. So it has to be capable to say real numbers.

**Comment by Apollon77** [comment]
From where the text are send to sayout state? A Script from you? Then you need to convert. The sayit adapter can not convert points to commas or such in general ...

Or do you have problems with Alexa command responses?! Then the Cloud Adapter that generates these values needs to convert - correct!

**Comment by Apollon77** [comment]
BTW: I added new error handling as "normal" in nodejs stuff to return a second parameter "err" to all callbacks to check if an error happened. Before errors were completely ignored for LIST returns and ended up is node-nut internal status being "waiting" forever. And on error the callback was never called at all, but this is not as awaited I think. So now callback is called but with an empty return, but a second error parameter.
It's a different behaviour, but should be not breaking at all .. 
Alternative (to make sure) you could increase version to 1.0.0 and then it should be no conflict at all when dependencies are set as usual

**Comment by derrapf** [comment]
>The sayit adapter can not convert points to commas or such in general
I don't want the sayit adaper it to convert decimal points to comms. 
I just want it to pronounce float values like "3.124" correctly.
I just want that the sentence 
"Pi is equal to 3.141"
is said correctly and not like 
"Pi is three-thousand one-hundred and forty one"

**Comment by Apollon77** [comment]
Did you checked the notes on https://github.com/ioBroker/ioBroker.sayit ?!
Or in this case also http://docs.aws.amazon.com/polly/latest/dg/supported-ssml.html#say-as-tag ... I think you need to add such infos in order to have the TTS enginge understand

**Comment by GermanBluefox** [comment]
```That is completely unusable.```
I marvel every time to such statements.

How must sayIt distinguish between 3.145 as 3145 and 3,145 decimal? What is the your problem to convert the number into 3,14? 

You build the text anyway somehow.

**Comment by derrapf** [comment]
Hi Bluefox
Maybe we have different expectations of how some things should work.
My point of view is the following:
"Sayit" is a adapter for iobroker. That means it should be able to deal with variable contents that iobroker provides. Mainly iobroker is a home-automation system that manages variable content of actor states and sensor values.
Sensor values are, without exception, float values which have the notation \<first digits\>.\<decimal digits\>.
A comma, as a separator for the thousands, normally is only used in commercial context what we do not have in a home automation environment (and if, then only for a minority of use cases).
So, of course I could dig in to all my scripts and kind of convert the real values coming from my sensors to a commercial notation, but in my opinion this is a workaround which shifts the correction of an adapter's issue to the user.
If a adapter is provided to be used with a home-automation system, then it should be able to deal with native data that this systems provides to it.
Just my two cents.

Ralf

**Comment by GermanBluefox** [comment]
Just now the point of view is that the user must create valid text, so the text will be valid pronounced.
If you can create PullRequest for this issue, we will consider it.

**Comment by derrapf** [comment]
Hi Bluefox

> Just now the point of view is that the user must create valid text, so the text will be valid pronounced.

The problem ist that "the user" not always will be capable to create valid text.
For example if the text is not generated by the user, but is coming from another adapter like dwd.
I cannot just replace "." with "," in large texts like they are coming from dwd, because they are not exclusively decimal points.

Ciao Ralf

**Comment by Apollon77** [comment]
And here you exactly hit the point ... Also iobroker has no option to modify the text send to the adapter and ioBroker will forward this test without any modifications to the TTS "provider", AWS Polly Webservice in this case. And the text is then interpreted and digitized into speech by Amazon in this case ...
So the only one with the "Most" control over the text which should be spoken is the user that generated the text ...

**Comment by derrapf** [comment]
>And here you exactly hit the point ... Also iobroker has no option to modify the text send to the adapter >and ioBroker will forward this test without any modifications to the TTS "provider", 

I know. But I hoped that there is some kind of configuration the adapter could do to Polly to adjust how things are interpreted.  Like decimal formats, date formats and so on. 

Ciao Ralf

**Comment by Apollon77** [comment]
And exactly this is only possible "in text" using SSML :-(

**Comment by derrapf** [comment]
Ok...I give it a try..
