### ISSUE TITLE
AWS Neural Engine Support

### ISSUE THREAD

**Issue by GrayDeathNBG** [ioBroker/ioBroker.sayit#201]
Hello,

can you add the NEURAL ENGINE support for the AWS Service?
the neural engine created files sounds much better then the standard files.

Thanx

**Comment by Assemblerguru** [comment]
Yes, this would also very interested for me

**Comment by neopholus** [comment]
As a quick fix you can do the following:
- Select a voice that is available as neural and as standard voice, see [here](https://docs.aws.amazon.com/polly/latest/dg/ntts-voices-main.html), e.g. "Vicki" for German or Ivy for English.
- Use ssh to log into your iobroker host
- `cd /opt/iobroker/node_modules/iobroker.sayit/lib/`
- `editor text2speech.js`
  - Search for "aws". A few lines below, there is a definition of a param-object:
```
       const params = {
                Text:         text,
                OutputFormat: 'mp3',
                TextType:     type,
                VoiceId:      sayitEngines[language].ename
            };

```
- Add the neural engine like following:
```
            const params = {
                Text:         text,
                Engine:       'neural',
                OutputFormat: 'mp3',
                TextType:     type,
                VoiceId:      sayitEngines[language].ename
            };

```
- Save the file
- `cd /opt/iobroker`
- `npm rebuild iobroker.sayit`
- `iobroker restart`

Now the neural voice should be active.

**Comment by Assemblerguru** [comment]
Thank you very much! It works perfect
