### ISSUE TITLE
V1.6.0 generates errors and stops

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.sayit#21]
Below is a log and the error is
`ReferenceError: path is not defined at Text2Speech.sayItGetSpeech (/opt/iobroker/node_modules/iobroker.sayit/lib/text2speech.js:479:36)`

I get this on all instances where I installed 1.6.0 over older 1.5.x 

`host.opi | 2017-09-25 15:09:59.099 | error | instance system.adapter.sayit.0 terminated with code 0 (OK)
-- | -- | -- | --
sayit.0 | 2017-09-25 15:09:59.070 | info | terminating
sayit.0 | 2017-09-25 15:09:59.046 | info | stopping...
sayit.0 | 2017-09-25 15:09:59.042 | error | at Timer.listOnTimeout (timers.js:214:5)
sayit.0 | 2017-09-25 15:09:59.042 | error | at tryOnTimeout (timers.js:250:5)
sayit.0 | 2017-09-25 15:09:59.042 | error | at ontimeout (timers.js:386:11)
sayit.0 | 2017-09-25 15:09:59.042 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
sayit.0 | 2017-09-25 15:09:59.042 | error | at Adapter.emit (events.js:191:7)
sayit.0 | 2017-09-25 15:09:59.042 | error | at emitTwo (events.js:106:13)
sayit.0 | 2017-09-25 15:09:59.042 | error | at Adapter. (/opt/iobroker/node_modules/iobroker.sayit/main.js:38:13)
sayit.0 | 2017-09-25 15:09:59.042 | error | at sayIt (/opt/iobroker/node_modules/iobroker.sayit/main.js:398:21)
sayit.0 | 2017-09-25 15:09:59.042 | error | at Text2Speech.sayItGetSpeech (/opt/iobroker/node_modules/iobroker.sayit/lib/text2speech.js:479:36)
sayit.0 | 2017-09-25 15:09:59.042 | error | ReferenceError: path is not defined
sayit.0 | 2017-09-25 15:09:59.041 | error | uncaught exception: path is not defined
sayit.0 | 2017-09-25 15:09:58.967 | info | saying: helligkeit hat 75
sayit.0 | 2017-09-25 15:07:53.473 | info | All files uploaded
sayit.0 | 2017-09-25 15:07:53.374 | info | Upload announce mp3 files
sayit.0 | 2017-09-25 15:07:53.358 | info | starting. Version 1.6.0 in /opt/iobroker/node_modules/iobroker.sayit, node: v6.11.3
sayit.0 | 2017-09-25 15:07:53.242 | info | States connected to redis: 127.0.0.1:6379
host.opi | 2017-09-25 15:07:50.851 | info | instance system.adapter.sayit.0 started with pid 19853
host.opi | 2017-09-25 15:07:20.814 | info | Restart adapter system.adapter.sayit.0 because enabled

`

**Comment by Apollon77** [comment]
see Forum Thread http://forum.iobroker.net/viewtopic.php?f=22&t=8196&e=1&view=unread#unread
: Fixed. Try 1.6.1 from Github"

**Comment by frankjoke** [comment]
Ok, tried 1.6.1 but another error shows up now:
`

sayit.0 | 2017-09-25 16:18:51.805 | info | terminating
-- | -- | -- | --
sayit.0 | 2017-09-25 16:18:51.786 | info | stopping...
sayit.0 | 2017-09-25 16:18:51.783 | error | at Timer.listOnTimeout (timers.js:214:5)
sayit.0 | 2017-09-25 16:18:51.783 | error | at tryOnTimeout (timers.js:250:5)
sayit.0 | 2017-09-25 16:18:51.783 | error | at ontimeout (timers.js:386:11)
sayit.0 | 2017-09-25 16:18:51.783 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
sayit.0 | 2017-09-25 16:18:51.783 | error | at Adapter.emit (events.js:191:7)
sayit.0 | 2017-09-25 16:18:51.783 | error | at emitTwo (events.js:106:13)
sayit.0 | 2017-09-25 16:18:51.783 | error | at Adapter. (/opt/iobroker/node_modules/iobroker.sayit/main.js:38:13)
sayit.0 | 2017-09-25 16:18:51.783 | error | at sayIt (/opt/iobroker/node_modules/iobroker.sayit/main.js:398:21)
sayit.0 | 2017-09-25 16:18:51.783 | error | at Text2Speech.sayItGetSpeech (/opt/iobroker/node_modules/iobroker.sayit/lib/text2speech.js:480:41)
sayit.0 | 2017-09-25 16:18:51.783 | error | ReferenceError: cacheDir is not defined
sayit.0 | 2017-09-25 16:18:51.782 | error | uncaught exception: cacheDir is not defined

`

**Comment by Apollon77** [comment]
Refactoring :-))
Try again please ... (changing blind, so sorry for the "Iterations")

**Comment by frankjoke** [comment]
Another error: ReferenceError: sayItSystemVolume is not defined, 

at sayItSystem (/opt/iobroker/node_modules/iobroker.sayit/lib/speech2device.js:398:9)
--

This function is defined as a property to the main class and not as a free function so it need to be called from a 'that' var or something else in free functions without reference to this!

**Comment by Apollon77** [comment]
The PR solved this?  Great!!

**Comment by frankjoke** [comment]
Yes.
