### ISSUE TITLE
null in file address

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.sayit#215]
**Describe the bug**  
I'm trying to send an alert text to the sonos, and I see that the address to the file in the log is incorrect. Instead of ip address "null"

**Screenshots & Logfiles**  
```
sonos.0 | 2022-05-23 17:19:39.601 | error | Cannot execute TTS: RequestFailedError: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2022-05-23 17:19:35.948 | info | try to control id sonos.0.root.192_168_5_115.tts with {"val":"70;http://null:8082/state/sayit.0.tts.mp3","ack":false,"ts":1653315575943,"q":0,"from":"system.adapter.sayit.0","user":"system.user.admin","lc":1653315426412}
sayit.0 | 2022-05-23 17:19:35.936 | info | Set "sonos.0.root.192_168_5_115.tts: 70;http://null:8082/state/sayit.0.tts.mp3
sayit.0 | 2022-05-23 17:19:35.925 | info | saying: Программа по захвату кожаных мешков активизирована.

```
![image](https://user-images.githubusercontent.com/37106885/169841594-5dfae931-a1fb-4c56-a571-90e16692a744.png)
![image](https://user-images.githubusercontent.com/37106885/169841706-df81abcc-416f-4d45-82f1-3791a1053cc3.png)

**Versions:**  
 - Adapter version: 1.12.6
 - JS-Controller version: 4.0.23
 - Node version: v14.19.2
 - NPM: 8.10.0
 - Operating system: RPI 4

**Additional context**  
similar issue discussed here, But no solution offered  - https://github.com/iobroker-community-adapters/ioBroker.chromecast/issues/105

**Comment by GermanBluefox** [comment]
PLease retest with 3.0.3
