### ISSUE TITLE
double output / volume ignored chromecast

### ISSUE THREAD

**Issue by Kev0123** [ioBroker/ioBroker.sayit#23]
if a anouncement is set the text will be played twice.

the adapter seems to hook the wrong datapoint for the volume of the chromecast.
it sets the player volume, not the volume under status, so the text will be at the same volume regardless what you put into the volume argument of sayit.

**Comment by Marty56** [comment]
I can confirm that the changing the volume in the sayit adapter has not effect.
I do not see in my setup that anouncements are played twice.

**Comment by Kev0123** [comment]
issue with double output is still persistant

**Comment by Apollon77** [comment]
Can you show the config of the adapter and also provide debug log of such a case?!

**Comment by Kev0123** [comment]
Here are the settings : ![image](https://user-images.githubusercontent.com/19821853/84505863-c2315c80-acbe-11ea-99f2-3f04952c2a51.png)
![image](https://user-images.githubusercontent.com/19821853/84505925-dbd2a400-acbe-11ea-9a58-32b78f55ea93.png)
`

javascript.0 | 2020-06-12 15:11:45.427 | info | (589) Stop script script.js.Skripte.Skript_1
-- | -- | -- | --
chromecast.0 | 2020-06-12 15:11:41.499 | info | (1429) Mini Wohnzimmer - getStatus
chromecast.0 | 2020-06-12 15:11:41.458 | info | (1429) Mini Wohnzimmer - queueRemove
chromecast.0 | 2020-06-12 15:11:41.361 | info | (1429) Mini Wohnzimmer - Playing - http://192.168.178.99:8082/state/sayit.0.tts.mp3
chromecast.0 | 2020-06-12 15:11:41.361 | info | (1429) Mini Wohnzimmer - Resumed after announcement
chromecast.0 | 2020-06-12 15:11:41.361 | info | (1429) Mini Wohnzimmer - setting volume to same value 70 - ignored
sayit.0 | 2020-06-12 15:11:40.128 | debug | (32712) chromecast.0.Mini_Wohnzimmer.player.announcement finished playing announcement: {"url":"http://192.168.178.99:8082/state/sayit.0.tts.mp3","volume":70}
sayit.0 | 2020-06-12 15:11:40.127 | debug | (32712) Duration "Test": 0
sayit.0 | 2020-06-12 15:11:40.126 | debug | (32712) chromecast.0.Mini_Wohnzimmer.player.announcement finished playing announcement: {"url":"http://192.168.178.99:8082/state/sayit.0.tts.mp3","volume":70}
chromecast.0 | 2020-06-12 15:11:40.102 | info | (1429) Mini Wohnzimmer - setting volume to same value 70 - ignored
chromecast.0 | 2020-06-12 15:11:40.102 | info | (1429) Mini Wohnzimmer - getStatus
chromecast.0 | 2020-06-12 15:11:40.090 | info | (1429) Mini Wohnzimmer - Playing - http://192.168.178.99:8082/state/sayit.0.tts.mp3
chromecast.0 | 2020-06-12 15:11:39.772 | info | (1429) Mini Wohnzimmer - queueInsert
chromecast.0 | 2020-06-12 15:11:39.771 | info | (1429) Mini Wohnzimmer - setting volume to same value 70 - ignored
chromecast.0 | 2020-06-12 15:11:39.771 | info | (1429) Mini Wohnzimmer - Finished playing announcement
chromecast.0 | 2020-06-12 15:11:39.712 | info | (1429) Mini Wohnzimmer - Closing mediaInfo
chromecast.0 | 2020-06-12 15:11:39.684 | info | (1429) Mini Wohnzimmer - getStatus
chromecast.0 | 2020-06-12 15:11:39.637 | info | (1429) Mini Wohnzimmer - queueInsert
chromecast.0 | 2020-06-12 15:11:39.599 | info | (1429) Mini Wohnzimmer - Closing mediaInfo
chromecast.0 | 2020-06-12 15:11:39.593 | info | (1429) Mini Wohnzimmer - Try to play announcement - "http://192.168.178.99:8082/state/sayit.0.tts.mp3"
sayit.0 | 2020-06-12 15:11:39.589 | debug | (32712) Duration "Test": 1
sayit.0 | 2020-06-12 15:11:39.588 | info | (32712) Set "chromecast.0.Mini_Wohnzimmer.player.announcement to {"url":"http://192.168.178.99:8082/state/sayit.0.tts.mp3","volume":70}
sayit.0 | 2020-06-12 15:11:39.584 | info | (32712) saying: Test
chromecast.0 | 2020-06-12 15:11:38.974 | info | (1429) Mini Wohnzimmer - Playing playlist with 1 items
chromecast.0 | 2020-06-12 15:11:38.972 | info | (1429) Mini Wohnzimmer - Playing - http://192.168.178.99:8082/state/sayit.0.tts.mp3
chromecast.0 | 2020-06-12 15:11:38.643 | warn | (1429) Mini Wohnzimmer - remaining item to play after announcement not found in the playlist -> remove status handled
chromecast.0 | 2020-06-12 15:11:38.595 | info | (1429) Mini Wohnzimmer - Try to play playlist with 1 items
chromecast.0 | 2020-06-12 15:11:38.595 | info | (1429) Mini Wohnzimmer - Closing mediaInfo
chromecast.0 | 2020-06-12 15:11:38.587 | info | (1429) Mini Wohnzimmer - Try to play url - http://192.168.178.99:8082/state/sayit.0.tts.mp3
chromecast.0 | 2020-06-12 15:11:38.586 | info | (1429) Mini Wohnzimmer - setting volume to same value 70 - ignored
chromecast.0 | 2020-06-12 15:11:38.586 | info | (1429) Mini Wohnzimmer - Try to play announcement - "http://192.168.178.99:8082/state/sayit.0.tts.mp3"
sayit.0 | 2020-06-12 15:11:38.582 | debug | (32712) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 1
sayit.0 | 2020-06-12 15:11:38.580 | info | (32712) Set "chromecast.0.Mini_Wohnzimmer.player.announcement to {"url":"http://192.168.178.99:8082/state/sayit.0.tts.mp3","volume":70}
sayit.0 | 2020-06-12 15:11:38.533 | info | (32712) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3
sayit.0 | 2020-06-12 15:11:38.530 | silly | (32712) States user redis pmessage sayit.0.*/sayit.0.tts.text:{"val":"Test","ack":false,"ts":1591967498525,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1591967266548}
javascript.0 | 2020-06-12 15:11:38.525 | info | (589) script.js.Skripte.Skript_1: registered 0 subscriptions and 0 schedules
javascript.0 | 2020-06-12 15:11:38.521 | info | (589) Start javascript script.js.Skripte.Skript_1

`
Here is the behaviour:
[https://youtu.be/pQN2GJrRMik](url)

**Comment by Apollon77** [comment]
Hm ... when I see and understand it correctly, it could bebalso that chromecast adapter is producing tis issue ... because sayit sends the announcement nd then the text ...

**Comment by KKief** [comment]
Same issue here. Completely the same situation as described above. Does not make a difference if I cast to a single Chromecast or a group of them. In addition, I will receive always the connection tone every time Im triggering the say.it command.

![image](https://user-images.githubusercontent.com/45283717/84661964-67487100-af1b-11ea-8b7e-223ebcc4155a.png)

triggered the blocky via double click to have the log snippet for entering here. This time it even echoed "Test" 3 times

![image](https://user-images.githubusercontent.com/45283717/84662177-bc848280-af1b-11ea-98c8-b58e17e1e875.png)
