### ISSUE TITLE
Amazon AWS Vicki

### ISSUE THREAD

**Issue by darkbrain85** [ioBroker/ioBroker.sayit#25]
Hi!

Is it possible to add German "Vicki" as AWS Polly voice? Vicki is available as voice in AWS console.

**Comment by larsdecker** [comment]
Yes it is possible. I have added it, into my Fork and hope that they will accept my pull request.

**Comment by larsdecker** [comment]
included in 4518e5ad33718cb917736d5d4c2041ca0de72aeb
Can be closed.
