### ISSUE TITLE
Plays old text instead of new one

### ISSUE THREAD

**Issue by mswiege** [ioBroker/ioBroker.sayit#255]
**Describe the bug**  
I'm setting multiple texts after another in my script, but the device is playing one text over and over again. It's a bit random which text is played, it seems that there is some kind of cache and even if I want to play a new text, the cached text is played until some "random" time where the cache is cleared, then a new text will be played, which itself then gets into the cache and gets played multiple times instead of each time a new text.

I tried setting clearQueue between the texts, but this doesn't change anything.

The log doesn't show anything usefull (even in "silly" level).

My settings:
- Type: Chromecast
- No bell file selected
- Use cache: No
- Device: chromecast.0.<id of Google Home device>
- TTS Engine: AWS Polly

**To Reproduce**  
The following script says three time "Hello Text 1" (or if run multiple times at some point it switches to one of the other numbers):
```
    setState(SAY_IT_ID + "clearQueue", true);    
    setState(SAY_IT_ID + "text", "100;<emphasis>Hello</emphasis> Text 1");
    await delay(5000);
    setState(SAY_IT_ID + "clearQueue", true);    
    setState(SAY_IT_ID + "text", "100;<emphasis>Hello</emphasis> Text 2");
    await delay(5000);
    setState(SAY_IT_ID + "clearQueue", true);    
    setState(SAY_IT_ID + "text", "100;<emphasis>Hello</emphasis> Text 3");
seconds.");
    await delay(5000);
```
The log this produces is:
```
debug | chromecast.0.<id>.player.announcement finished playing announcement: {"url":"http://<iobrokerIP:Port>/sayit.0/tts.mp3","volume":100}
info | Set "chromecast.0.546009dfbd94.player.announcement to {"url":"http://192.168.1.50:8082/sayit.0/tts.mp3","volume":100}
info | saying: <emphasis>Hello</emphasis> Text 3
debug | chromecast.0.<id>.player.announcement finished playing announcement: {"url":"http://<iobrokerIP:Port>/sayit.0/tts.mp3","volume":100}
info | Set "chromecast.0.546009dfbd94.player.announcement to {"url":"http://192.168.1.50:8082/sayit.0/tts.mp3","volume":100}
info | saying: <emphasis>Hello</emphasis> Text 2
debug | chromecast.0.<id>.player.announcement finished playing announcement: {"url":"http://<iobrokerIP:Port>/sayit.0/tts.mp3","volume":100}
info | Set "chromecast.0.546009dfbd94.player.announcement to {"url":"http://192.168.1.50:8082/sayit.0/tts.mp3","volume":100}
info | saying: <emphasis>Hello</emphasis> Text 1
```
So the log "claims" to play the correct text, but the tts.mp3 seems to be always the same.

**Expected behavior**  
If "text" is set, it always plays the text that is set.

**Versions:**  
 - Adapter version: 3.0.0
 - chromecast Adapter version: 3.1.0
 - JS-Controller version: 4.0.24
 - Node version: 16.19.0
 - Operating system: RaspPi

**Comment by GermanBluefox** [comment]
Please retest with 3.0.2
