### ISSUE TITLE
Sonos devices cannot be selected

### ISSUE THREAD

**Issue by chrisret0** [ioBroker/ioBroker.sayit#264]
**Describe the bug**  
The Sonos devices cannot be selected in the instance config. Test works fine. However, it will play on all devices. Individuals cannot be selected.

If you call sayit in javascript, nothing will be played. The web adapter is installed. Sonos access works fine.
If i control the sayit object all works fine but on all sonos devices in the house.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
Sonos Devices can be selected as in den Versions 1.x
<img width="845" alt="sayit-img01" src="https://github.com/ioBroker/ioBroker.sayit/assets/82751874/eadd1e8e-20c7-4141-9e06-e1b7f1805729">

**Screenshots & Logfiles**  
<img width="984" alt="sayit-img03" src="https://github.com/ioBroker/ioBroker.sayit/assets/82751874/b2c30a1d-f3a2-408b-9e9d-a80477e39d14">

<img width="1134" alt="sayit-img04" src="https://github.com/ioBroker/ioBroker.sayit/assets/82751874/28215143-e8e0-48f1-af21-9a2222f0279d">

<img width="882" alt="sayit-img05" src="https://github.com/ioBroker/ioBroker.sayit/assets/82751874/49c6a636-33db-408b-a0d8-c2e086434f53">

**Versions:**  
 - Adapter version: 
sayit v3.05
web v4.3.0
sonos v2.3.1
 - JS-Controller version: 4.0.24
 - Node version: v14.21.3
 - Operating system: raspberry os

**Additional context**

**Comment by HJS72** [comment]
Exactly the same behavior here with following config:

sayit v3.05
web v5.5.3
sonos v2.3.1
Node version: v18.17
Operating system:debian/proxmox

**Comment by RossMax2** [comment]
Same Error
sayit v 3.05
web v 4.3.0
sonos v 2.3.1
Node v 18.17
buantet-iobroker in Synology Container

**Comment by hesterik** [comment]
I do have the same issue:
sayit v.05
webserver v6.1.4 and v6.1.10
sonos v2.3.1. and  issues is not solved with v.3.0.0
Node version: v18.17.1

**Comment by kptkip** [comment]
+1

**Comment by trollvottel** [comment]
+1

**Comment by thogens** [comment]
+1

**Comment by thogens** [comment]
Any news here? Still facing this issue after trying x reinstallations etc....

**Comment by chrisret0** [comment]
In the meantime, I have found a solution. Sonos must be addressed via the API. On the Say-It adapter you just have to configure die Speacht2Text Part.... all outher stuff doesn't matter.

This link shows how to set it up: [https://github.com/Homoran/iobroker.sonos_api]

**Comment by thogens** [comment]
What about playing .mp3? Does it work as well?

**Comment by chrisret0** [comment]
Yes that works too: On this link you find the hole documentation. [Link](https://github.com/jishi/node-sonos-http-api#usage) 
What you search for is Clips....

**Comment by trollvottel** [comment]
You sure? I run a dockered ioBroker and don't want to fiddle on the console, adapter strongly preferred!

**Comment by chrisret0** [comment]
Then just make a new Docker with the sonos http api and everything is fine

**Comment by trollvottel** [comment]
Is there a Docker image available?

**Comment by trollvottel** [comment]
Those I found on Docher Hub were last updated 5+ years ago.
