### ISSUE TITLE
mp3 wird nicht korrekt erzeugt !

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sayit#265]
vgl. auch:
https://forum.iobroker.net/topic/66410/sayit-mp3-erzeugen-geht-nicht-mehr

Fazit:
Mit der Version 1.13.0 klappt es.
Mit der aktuellen 3.0.5 klappt es nicht.

**Comment by bahnuhr** [comment]
im log kommt auch sowas:
<html>
<body>


sayit.2 | 2023-06-25 11:58:58.906 | error | Error: dns service error: unknown
-- | -- | -- | --
sayit.2 | 2023-06-25 11:58:38.710 | error | amixer is not available, so you may hear no audio. Install manually!
sayit.2 | 2023-06-25 11:58:38.702 | error | sayIt.play: there was an error while playing the file: Error: spawn amixer ENOENT
sayit.2 | 2023-06-25 11:58:38.319 | info | Upload announce mp3 files


</body>
</html>

**Comment by Apollon77** [comment]
> Error: spawn amixer ENOENT

besagt das das nötige Tool nicht installiert ist?! Bitte Readme prüfen und "amixer" installieren

**Comment by bahnuhr** [comment]
Hatte mit @thomas-braun geklärt, dass der Rechner ja keine Lautsprecher hat (auch in o.g. thread).
somit ist amixer nicht notwendig.

**Comment by bahnuhr** [comment]
Das Problem war:
https://forum.iobroker.net/topic/60071/ank%C3%BCndigung-deprecation-binary-states-js-controller-5-0

Also: binary states nicht mehr vorhanden (DP: mp3 wurde entfernt)
Anderer Workflow gefunden mit kopieren der tts.mp3.
