### ISSUE TITLE
Keine Ansage mehr wenn im JS oder Blockly Script z.B. der Trigger geändert wird.

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.sayit#269]
Ich habe in zwei vorhandenen Blockly Scripten nur den Trigger geändert und die Änderung gespeichert. Im Anschluss funktioniert die Ansage nicht mehr.

Trigger in einfachem Ansage Blockly oder JS ändern.

Ansagen sollten weiterhin funktionieren

Die ersten logs können ab hier gefunden werden, weitere könne geliefert werden wenn mir einer sagt was genau benötigt wird.

https://forum.iobroker.net/topic/66708/sayit-block-funktioniert-nicht-mehr/6?_=1688623391137#

**Versions:**  
 - Adapter version: 3.0.5
 - JS-Controller version: 5.0.6
 - Node version: 18.16.1
 - Operating system: Bullseye

**Comment by d0nnergurke** [comment]
Sames as: #267

**Comment by DaniSchaer** [comment]
same here!
3.0.5 (2023-04-17)
...
(klein0r) Used sendTo instead of setState in blockly

after save the Blokly it will change from  "setState" to "sendTo". SendTo does not work!
@klein0r can you fix  this?

**Comment by klein0r** [comment]
@DaniSchaer I've changed that in this PR #225
But my changes have been rejected and just some changes were copied to the new version 😢

**Comment by Krys91** [comment]
Hat man ungefähr einen Zeitraum,. wann eine neue Version erscheint?

**Comment by wendy2702** [comment]
Any news update on this?

**Comment by wendy2702** [comment]
> @DaniSchaer I've changed that in this PR #225
> 
> But my changes have been rejected and just some changes were copied to the new version 😢 

Kannst du mir verraten was ich wo bei mir lokal ändern muss damit es wieder funktioniert?

**Comment by maxpd1** [comment]
Same problem here since months. 
Messages to a Group of Google Homes are working.
Messages to single Google Homes aren't due to timeout message according to error log.

**Comment by DaniSchaer** [comment]
> > @DaniSchaer I've changed that in this PR #225
> > But my changes have been rejected and just some changes were copied to the new version 😢
> 
> Kannst du mir verraten was ich wo bei mir lokal ändern muss damit es wieder funktioniert?

Du musst zurück auf Version 3.0.0 und die 3.0.5 ignorieren

**Comment by wendy2702** [comment]
Wird das Problem eventuell noch gelöst?

**Comment by Apollon77** [comment]
Hast Du deine Skripte mal mit aktuellem JS und Adaopter leicht editiert sodass der JS Code neu erzeugt wird?

**Comment by DaniSchaer** [comment]
> Hast Du deine Skripte mal mit aktuellem JS und Adaopter leicht editiert sodass der JS Code neu erzeugt wird?

Ja als Blockly etwas ändern und neu speichern . Auf Script umschalten und kontrollieren ob setState anstelle von sendTo steht.

**Comment by wendy2702** [comment]
> Hast Du deine Skripte mal mit aktuellem JS und Adaopter leicht editiert sodass der JS Code neu erzeugt wird?

Nein, werde ich aber testen.

Sollte es denn damit funktionieren?

**Comment by Brainbug01** [comment]
@klein0r kannst du sagen ob das Problem mit 4.0.1 behoben ist?

**Comment by klein0r** [comment]
@Brainbug01 Ich habe an dem Adapter lange nichts gemacht, müsste ich auch testen

**Comment by DaniSchaer** [comment]
@klein0r wärst du so nett und machst deine Änderung zu sendTo rückgängig? Der momentane Zustand ist wirklich sehr unglücklich. Besten Dank

**Comment by Brainbug01** [comment]
> I've changed that in this PR #225 But my changes have been rejected and just some changes were copied to the new version 😢

@klein0r du schreibst ja hier das deine Änderungen abgelehnt wurden und in die neue Version übernommen wurden. Das wäre cool wenn das Blockly wieder funktioniert nach dem Update.

**Comment by Brainbug01** [comment]
Update auf 4.0.1 bringt den selben Fehler:
Das Blockly aus Sendto wird nach dem speichern geändert in sendTo und dann kommt keine Sprachausgabe:
![image](https://github.com/ioBroker/ioBroker.sayit/assets/35106961/d538b420-e9d3-4fbe-9938-aac12bb58e00)

``
sendTo("sayit.1", "say", { text: 'text' })
;setState('sayit.1.tts.text' /* Text to speech */, 'text');
``

Wenn man 4.0.1 verwenden möchte dann muss man das Sendto Blockly auf steuere umstellen.

**Comment by wendy2702** [comment]
Sayit funktioniert bei mir seit Version 4.0.1 überhaupt nicht mehr. Auch meine Scripte mit Rules bringen keine Ansage mehr. Ebenfall bekomme ich keine Ansage beim Drücken des TEST Button.

Wenn ich die Instanz öffne erhalte ich diese Fehler im log:

```
2024-06-04 17:50:33.808  - info: sayit.0 (880) saying: hallo
2024-06-04 17:50:57.236  - error: sayit.0 (880) Error: The module '/opt/iobroker/node_modules/mdns/build/Release/dns_sd_bindings.node'
2024-06-04 17:51:15.571  - error: sayit.0 (880) Error: The module '/opt/iobroker/node_modules/mdns/build/Release/dns_sd_bindings.node'

```

So sehen die Einstellungen nach Update auf 4.0.1 aus:

![grafik](https://github.com/ioBroker/ioBroker.sayit/assets/33424168/e1925a2c-af55-4aa0-91b4-064130669bf2)

Wenn ich mit den Einstellungen auf Test drücke kommt das 

`2024-06-04 18:01:02.628  - error: sayit.0 (44931) Cannot control browser via vis1, because vis.0.* objects found
`

Stell ich das um auf VIS.0 (veraltet) und Drücke "Test" kommt dasselbe:

`2024-06-04 18:02:29.266  - error: sayit.0 (44981) Cannot control browser via vis1, because vis.0.* objects found`

Stell ich auf VIS-2.0 (neu) um erhalte ich das:

`2024-06-04 18:03:54.981  - error: sayit.0 (45001) Cannot control browser via vis1, because vis-2.0.* objects found`

**Comment by ipod86** [comment]
Bei mir klappt es sporadisch nicht.

Bei mir folgendes Skript.

![Screenshot_20240622_211400_Chrome](https://github.com/ioBroker/ioBroker.sayit/assets/66136363/06dcf013-3aad-46af-b79b-c3bed5ef287c)

**Comment by GermanBluefox** [comment]
Please test 4.0.4

**Comment by wendy2702** [comment]
Working for me with 4.0.4
