### ISSUE TITLE
A null error in the log when sending text (v1.6.6)

### ISSUE THREAD

**Issue by electric69** [ioBroker/ioBroker.sayit#27]
![pic_319](https://user-images.githubusercontent.com/9362080/35481376-746150fe-0433-11e8-887a-404f105132d7.jpg)
An error occurs if a new phrase is played, which is not in the cache

**Comment by electric69** [comment]
Log in debug-mode:
![pic_320](https://user-images.githubusercontent.com/9362080/35481479-59f2aed2-0435-11e8-9200-f746084341ca.jpg)

**Comment by Apollon77** [comment]
fixed on Github
