### ISSUE TITLE
SayIt - Objekte - Werte Feld lässt sich mit Admin 3.1.4 nicht beschreiben

### ISSUE THREAD

**Issue by TeraX** [ioBroker/ioBroker.sayit#28]
Das Wertefeld in Admin 3.1.4 lässt sich beim Sayit Adapter - Text nicht beschreiben.
Im Wertefeld für die Volume gibt es keine Probleme.
In den Einstellungen für die Text Zeile ist der Haken für Lesen und Editieren gesetzt (Standard Einstellung)

*** Fehlerbeschreibung auf Admin 3.1.4 aktualisiert ***
*** Ich verwende SayIt Adapter v1.6.6 ***

Getestet mit 
Chrome 63.0.3239.132
IEdge 41.16299.15.0
FireFox  58.0 (64-Bit)

![image](https://user-images.githubusercontent.com/912577/35485384-590155bc-045f-11e8-82d3-4365619d2fc4.png)

![image](https://user-images.githubusercontent.com/912577/35485409-ac3312f2-045f-11e8-8875-6dda08bdf9e3.png)

**Comment by Apollon77** [comment]
Geht ein Doppelklick? Ich hatte mal den Effekt das leere Felder bei einem Doppelklick einen eingabedialog öffnen. Bei Feldern mit einem Wert könnte man direkt editieren.

**Comment by TeraX** [comment]
Ein Doppelklick für "text" klappt leider auch nicht.
Bei Volume klappt es mit Einfach- und dem Doppelklick

**Comment by GermanBluefox** [comment]
Duplicate
