### ISSUE TITLE
Error: Null when Sonos was off

### ISSUE THREAD

**Issue by baeckerman83** [ioBroker/ioBroker.sayit#30]
Hi!
I've seen "Error: null" from sayit in my log file. I figured out, that this happend when Sonos was off and doesn't play anything but sayit want's to say something. Normaly sayit saves the state and restarts the state after the sayit file is over. But because there was nothing played before sayit file there comes an error: null.

**Comment by GermanBluefox** [comment]
Which version do you have?
With this https://github.com/ioBroker/ioBroker.sayit/commit/950488e6f3d78b15d5ba4f25940f75305442684a it must be fixed.

**Comment by baeckerman83** [comment]
Hi!
I use version 1.6.6 and there is no update on the iobroker admin interface.

**Comment by Apollon77** [comment]
This version is only available on Github (Custom Install) because we want test first, i can release it later today

**Comment by baeckerman83** [comment]
Ok. Thank you! I'll change it in my code by my self.


Am 05.02.18 um 16:39 schrieb Ingo Fischer:

**Comment by Apollon77** [comment]
1.6.7 released
