### ISSUE TITLE
Unterschiedliche Ausgabe unter 35 Sekunden 

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.sayit#300]
Aktuell ist die Ausgabe von Textänderungen auf 35 Sekunden begrenzt. Sendet man innerhalb dieser 35 Sekunden einen neuen Text wird der zuvor gesendete Text nochmals abgespielt. Erst ab 35 Sekunden wird die Änderung übernommen und der neue Text wird verwendet. 

Ist es möglich Textänderungen ohne Wartezeit auszugehen?

V3.0.0 mit Google Mini

**Comment by smalltower1** [comment]
Ich nutze die Version 3.0.0, da die 3.0.5 nicht richtig funktioniert (siehe mein andere Issue), habe aber das gleiche Problem mit wiederholungen.

**Comment by Brainbug01** [comment]
4.0.1 und dem steuere Block funktioniert die Ausgabe von unterschiedlichen Texten sofort.
![image](https://github.com/ioBroker/ioBroker.sayit/assets/35106961/a3f790c3-79ff-4545-97bf-7e3d1db7c608)
