### ISSUE TITLE
sinnlose Fehlermeldung sayit.1	2018-02-07 06:43:04.723	error	null

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.sayit#31]
Ab und zu gibt der sayit Adapter folgende Fehlermeldung aus.

sayit.1 | 2018-02-07 06:43:04.723 | error | null
-- | -- | -- | --

Der sayit Adapter funktioniert dennoch. Die Fehlermeldung ist für den Nutzer sinnlos und sollte entfernt werden.

**Comment by Apollon77** [comment]
Bitte aktuellste Version (latest repo/GitHub) testen. wurde gefixt
