### ISSUE TITLE
Multiple google home => wrong assignment

### ISSUE THREAD

**Issue by cimba007** [ioBroker/ioBroker.sayit#34]
I got 2 google home mini which I want to address seperatly.

![image](https://user-images.githubusercontent.com/3453121/37537191-10705f74-294d-11e8-9e25-617c67a2de9c.png)
![image](https://user-images.githubusercontent.com/3453121/37537204-17bb2cbe-294d-11e8-9b02-dd090a77d680.png)

![image](https://user-images.githubusercontent.com/3453121/37537216-233e9cb0-294d-11e8-9e26-0e9e30c745c2.png)

Both speakers say "Dies ist ein Test von Google Home null"
![image](https://user-images.githubusercontent.com/3453121/37537343-8a73a222-294d-11e8-9647-f2c54d09fafc.png)

Both speakers say "Dies ist ein Test von Google Home eins"
![image](https://user-images.githubusercontent.com/3453121/37537371-9c22edde-294d-11e8-85c3-fa3bfa40dba4.png)

The problem is that both mp3-files have the same content:

http://192.168.178.56:8082/state/sayit.0.tts.mp3
http://192.168.178.56:8082/state/sayit.1.tts.mp3

althouth the ttl text is different:

de;40;Dies ist ein Test von Google Home eins
de;40;Dies ist ein Test von Google Home null

Download and rename to just *.mp3
![sayit 0 tts mp3](https://user-images.githubusercontent.com/3453121/37537629-7b5f9632-294e-11e8-96e0-b2a1294f242d.png)
![sayit 1 tts mp3](https://user-images.githubusercontent.com/3453121/37537630-7b850dae-294e-11e8-8836-993a6f0313ec.png)

My guess is that both instances use the same mp3 file .. maybe add the instance id (0 or 1) to the filename

![image](https://user-images.githubusercontent.com/3453121/37538051-c8d82fd6-294f-11e8-9cf2-053decca70a2.png)

**Comment by BuZZy1337** [comment]
I will take care of this issue but i dont have any google home hardware at home..
Are you registered on forum.iobroker.net?
If yes, please tell me your username .. i will send you a private message for testing the changes.

Thanks.

**Comment by cimba007** [comment]
@BuZZy1337 Hi and thanks. I am registered at the iobroker forum with the same username: cimba007.

**Comment by BuZZy1337** [comment]
I sent you some instructions how to test the changes via private Message.
Please report back the results of your tests.
Thanks. :+1:

**Comment by cimba007** [comment]
@BuZZy1337 Thanks for providing me with an updated version. I used the following code for my test:

```
          setState("sayit.0.tts.text", "de;50;Test eins");
          setState("sayit.1.tts.text", "de;50;Test zwei");
```

Both messages were played simultaneously on the according speakers. Seems to have solved the problem! Good work!

**Comment by GermanBluefox** [comment]
..But sendTo must work anyway.

**Comment by BuZZy1337** [comment]
PR #39 is ready for this issue.
