### ISSUE TITLE
Error: Load failed

### ISSUE THREAD

**Issue by cimba007** [ioBroker/ioBroker.sayit#36]
Any idea where this error might come from? "Load failed" doesn't even exist in the github src-code.

```
sayit.0 | 2018-03-31 01:07:41.400 | error | Error: Load failed
-- | -- | -- | --
sayit.0 | 2018-03-31 01:07:41.395 | error | Error: Load failed
sayit.1 | 2018-03-31 01:07:41.366 | error | Error: Load failed
sayit.1 | 2018-03-31 01:07:41.360 | error | Error: Load failed
sayit.1 | 2018-03-31 01:07:38.389 | info | saying: Alarm! Da ist etwas an der Terrassentür los!
sayit.0 | 2018-03-31 01:07:38.391 | info | saying: Alarm! Da ist etwas an der Terrassentür los!
```

**Comment by BuZZy1337** [comment]
If the adapter is silent and no sound is coming out of your speaker, then i 
guess maybe the adapter could not load the text to speech mp3 file from the 
server. Are you using the cloud in the sayit adapter settings?

**Comment by cimba007** [comment]
I just came to the same conclusion! I tried to enable caching and noticed:

![image](https://user-images.githubusercontent.com/3453121/38163303-3222d056-34f2-11e8-900f-41ddd80ec977.png)

I guess that I enabled authentification on the web.0 instance and just created a web.1 instance without authentification which is not accessible from the internet.

@BuZZy1337 Thanks ;-)
