### ISSUE TITLE
sayit.0.tts.mp3 filled only for sonos and browser.

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.sayit#37]
Make it settable to upload the file for other outputs too.

**Comment by BuZZy1337** [comment]
Could you give an example what you mean with "other outputs"?

**Comment by BuZZy1337** [comment]
.. now i know what you mean .. No example needed.. :smile:

**Comment by BuZZy1337** [comment]
Is that https://github.com/ioBroker/ioBroker.sayit/pull/38 okay for you? :smiley: 
Or do you have other intentions / thoughts about that?

**Comment by BuZZy1337** [comment]
@Apollon77 i think this issue is solved and should be closed.. :relaxed:
