### ISSUE TITLE
SayIt 1.7.0 ->cannot upload file

### ISSUE THREAD

**Issue by PrinzEisenherz1** [ioBroker/ioBroker.sayit#44]
Hatte mit der neuen Version heute morgen folgende Fehler im log
`sayit.0 Cannot upload file "/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3" to state: Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3'
`
Gruß
Johnny

**Comment by BuZZy1337** [comment]
Den Fehler kann ich nicht bestätigen.
War das ein einmaliger Fehler oder taucht der jedes mal auf wenn du über Sayit etwas ausgeben lassen willst?

**Comment by GermanBluefox** [comment]
Welche Einstellungen hast du?

**Comment by PrinzEisenherz1** [comment]
Die Fehlermeldung kommt sporadisch.
Hier meine Config

![sayit-config](https://user-images.githubusercontent.com/17569151/41291391-d68927e4-6e4f-11e8-8cff-f6e55e27c747.png)

**Comment by PrinzEisenherz1** [comment]
Heute morgen die selbe Fehlermeldung.
Ich lasse mir Morgens immer ne Ansage ausgeben und da steigt sayit jetzt aus.
Beispiel unter sayit.0.tts.text
`100;Guten Morgen, heute ist Mittwoch der 13te Juni 2018. Es ist7  Uhr und 1  Minuten. Die Aussentemperatur beträgt 12,2 Grad. Wetter Bedingungen,Bedeckt .`
Bis einschließlich Version 1.6.7 hat alles bestens geklappt. Bei der Version 1.6.8 ging das schon nicht mehr

**Comment by BuZZy1337** [comment]
Bitte nochmal von Github installieren und erneut versuchen.
(Siehe https://forum.iobroker.net/post/233427 für mehr Informationen)
