### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.sayit#55]
No idea why .. doesn't work (anymore) .. now playing never true .. mp3 rendered perfectly well .. sonos adapter correctly configured .. web adapter available. Quite frustrating :-(

**Comment by BuZZy1337** [comment]
Please give some more information .. Config of the Adapter, Error-Message from the Logs,..?

**Comment by daniel-lo** [comment]
![sayit](https://user-images.githubusercontent.com/4311558/53559092-ab0e4000-3b49-11e9-8258-38e29969f37f.png)

**Comment by daniel-lo** [comment]
https://forum.iobroker.net/topic/15955/sayit-spielt-musik-ab

**Comment by daniel-lo** [comment]
It's been a while since I tried .. I moved to alexa for speach output because I had too many probs.
