### ISSUE TITLE
sayit 1.7.0 gong.mp3  

### ISSUE THREAD

**Issue by salambelgord** [ioBroker/ioBroker.sayit#57]
![default](https://user-images.githubusercontent.com/27768450/48371664-7a56e780-e6cd-11e8-8c6b-ca407d9cbad3.png)
Нет возможности выбрать файл извещения. Только -none

**Comment by om2804** [comment]
If you upload a file, you can select the file. This is Bug

**Comment by Apollon77** [comment]
fixed?

**Comment by om2804** [comment]
1.7.0 not fixed
1.8.2 not fixed

**Comment by Apollon77** [comment]
and 1.9.2 from github?

**Comment by om2804** [comment]
> and 1.9.2 from github?

1.9.4 from github - not fixed

**Comment by Apollon77** [comment]
Ok can you please then tell in more detail what exactly is the problem? The issue description is currently not that helpful

**Comment by om2804** [comment]
![1](https://user-images.githubusercontent.com/2576620/81912735-49f84e00-95cf-11ea-8fcd-82fa95cd5dc8.gif)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by GermanBluefox** [comment]
Test 1.9.6

**Comment by om2804** [comment]
> Test 1.9.6

fixed!
