### ISSUE TITLE
Add another language on Google

### ISSUE THREAD

**Issue by birdoplo** [ioBroker/ioBroker.sayit#59]
Please add Ukrainian langue to the Google conversation list
![default](https://user-images.githubusercontent.com/46086380/50385997-64364100-06e7-11e9-957d-033bb83afc34.JPG)

**Comment by larsdecker** [comment]
See https://github.com/ioBroker/ioBroker.sayit/pull/73

**Comment by larsdecker** [comment]
@birdoplo  Can you please check the language?

**Comment by birdoplo** [comment]
> @birdoplo Can you please check the language?

How do I update the driver? I have the latest version 1.7.0.
![Снимок](https://user-images.githubusercontent.com/46086380/54780311-149ddd80-4c22-11e9-9e06-de78e17e0ed6.JPG)

**Comment by larsdecker** [comment]
Indeed, there is the old version on npm. Only the author of the repo can update it on NPM.

<img width="139" alt="Bildschirmfoto 2019-03-21 um 22 07 02" src="https://user-images.githubusercontent.com/1968186/54785179-d9051280-4c25-11e9-8fe5-e9d5e1b28941.png">

But you can install the version manually via Github. Click on the Github icon (at the adapter) -> Custom -> Enter the URL (https://github.com/ioBroker/ioBroker.sayit) and click Install.

**Comment by birdoplo** [comment]
it work. Thank you very much

**Comment by larsdecker** [comment]
Please close the issue, when it is working correctly.
