### ISSUE TITLE
Lautstärkenanpassung greift nicht mehr

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.sayit#6]
"de;70;dies ist ein Text"

Die Lautstärke (hier 7=) greift nicht mehr.

Der Text wird immer mit der vollen Lautstärke abgespielt, egal welche Lautstärke übergeben wird.
Der Ankündigungsgong verändert sich von der Lautstärke her.

Getestet mit dem Sonso Adapter.

**Comment by Marty56** [comment]
I am seeing the same bug with google chromecast.
https://github.com/angelnu/ioBroker.chromecast/issues/30

I was not sure where to put the issue but it seems to be more a "sayit" adapter issue.

**Comment by maxpd1** [comment]
same here. loudness has no effect on newest version of sayit adapter and google home mini as speaker.
