### ISSUE TITLE
cosmetical issues

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.sayit#64]
Hi, using Chrome as Browser and displaying the settings for SayIt Instances i found some cosmetical issues.

Please see attached Screenshots.

Something is overlapping and using Google (Sayit.0) their is no description for the "suchen" field.

![sayit_0](https://user-images.githubusercontent.com/33424168/51838754-9569e880-2307-11e9-8d49-bd5428745f21.jpg)
![sayit_1](https://user-images.githubusercontent.com/33424168/51838767-9bf86000-2307-11e9-97e4-67c74f79ee3c.jpg)

**Comment by GermanBluefox** [comment]
Please check 1.9.6
