### ISSUE TITLE
MediaPlayer24 geht nicht mehr

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sayit#68]
Hatte seit Monaten eingestellt:
MediaPlayer24 und die IP des Tablets.

Jetzt geht dies nicht mehr.
Als Fehlermeldung kommt:
Cannot upload file "C:\ioBroker\node_modules\iobroker.sayit\sayit.0.say.mp3" to state: Error: ENOENT: no such file or directory, open 'C:\ioBroker\node_modules\iobroker.sayit\sayit.0.say.mp3'

Was wurde geändert?
Oder was mich ich tun damit dies wieder funktioniert?

**Comment by BuZZy1337** [comment]
Bitte die aktuelle Version von Github installieren und gucken ob der Fehler behoben ist.

**Comment by bahnuhr** [comment]
Ich glaube es läuft jetzt.
Danke schön.
