### ISSUE TITLE
upgrade von 1.6 auf 1.7 ohne Funktion

### ISSUE THREAD

**Issue by totocotonio** [ioBroker/ioBroker.sayit#75]
Nach der Upgrade auf 1.7 kommt dieser Fehler im Log

Cannot upload file "/opt/iobroker/node_modules/iobroker.sayit/sayit.0.say.mp3" to state: Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.sayit/sayit.0.say.mp3'

Schreibrechte liegen vor.

**Comment by Apollon77** [comment]
Welchem user gehört das verzeichnis? Unetr welchem User läuft ioBroker?

**Comment by totocotonio** [comment]
Hi,
danke für Deine schnelle Antwort. Dutchman hat ihn eingerichtet. In einem ganz normalen Docker container

**Comment by Apollon77** [comment]
fixed?
