### ISSUE TITLE
Volume control not working

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.sayit#77]
I am using version 1.7.0 of sayit and browser as output channel.
The playback is using an Android tablet with fully as browser.
What I notice is that the volume control doesn't work at all, it always plays at max. no matter if I set the volume globally or directly in the output.

**Comment by maxpd1** [comment]
same here. loudness has no effect on newest version of sayit adapter and google home mini as speaker.

**Comment by capitaenz** [comment]
Same here

**Comment by Karatekid2407** [comment]
Same on my side with Sonos and Google Nest Mini
