### ISSUE TITLE
Please check ioBroker.sayit with js-controller 2.0

### ISSUE THREAD

**Issue by ioBrokerChecker** [ioBroker/ioBroker.sayit#81]
Hi,

the new js-controller 2.0 will come into latest repository in the next days and we want to make sure that all adapters are working well. We already did a 2 weeks Beta test and so some adapter were aleady checked and some needed slight adjustments.

You can find more information in https://github.com/ioBroker/ioBroker.js-controller/issues/482 and in the ioBroker Forum. If you have more technical questions please write in the referenced issue or in the Developer thread please. General questions are best in the genral thread.

Please update your systems to js-controller 2.0 and check your adapter.

Please close this issue once you have checked your adapter or received successfull reports from users.

Thank you very much for your support. Please contact us in the other Threads or Forum on any question.

**Comment by RESDE** [comment]
Dear developers,

the sayit controler is not working:
dapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!
I did restart of adapter and complete iobroker no change. Error is coming up.

In addition the sayit adapte ris not pushing an entry into the sonos adapter (version 2.0.1) under tss. Any ideas solutions for this?
So the adpater is not working properly 
Thank you very much.

**Comment by Apollon77** [comment]
The "error" you say is just a warning without any negative effect for now.

**Comment by Apollon77** [comment]
for other topic please create a new issue if none is already there!
