### ISSUE TITLE
Caching in Yandex Russian does not work.

### ISSUE THREAD

**Issue by ded000** [ioBroker/ioBroker.sayit#83]
Equal messages are written to the cache. Files are not used from the cache.

log-
2020-01-12 10:53:51.242  - .[32minfo.[39m: sayit.0 (173990) saying: 23:00
2020-01-12 10:53:51.851  - .[32minfo.[39m: sayit.0 (173990) Copied file "/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3" to "/opt/iobroker/cache/686ed27b3ef3efad9c53409a4
b864646.mp3"
2020-01-12 10:53:54.950  - .[32minfo.[39m: sayit.0 (173990) saying: 23:00
2020-01-12 10:53:55.536  - .[32minfo.[39m: sayit.0 (173990) Copied file "/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3" to "/opt/iobroker/cache/686ed27b3ef3efad9c53409a4
b864646.mp3"
2020-01-12 10:53:58.800  - .[32minfo.[39m: sayit.0 (173990) saying: 23:00
2020-01-12 10:53:59.349  - .[32minfo.[39m: sayit.0 (173990) Copied file "/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3" to "/opt/iobroker/cache/686ed27b3ef3efad9c53409a4
b864646.mp3"
2020-01-12 10:54:00.001  - .[32minfo.[39m: javascript.0 (1940) script.js.Testt.ParserFile+Voda: звук-- false
2020-01-12 10:54:02.760  - .[32minfo.[39m: sayit.0 (173990) saying: 23:00

**Comment by Apollon77** [comment]
Please test 1.9.8 from Github/latest and turn on debug log and post log please

**Comment by ded000** [comment]
sayit.0 | 2020-06-14 17:13:54.620 | debug | (694289) Duration "23:00": 0
-- | -- | -- | --
sayit.0 | 2020-06-14 17:13:54.612 | info | (694289) Copied file "/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3" to "/opt/iobroker/cache/686ed27b3ef3efad9c53409a4b864646.mp3"
sayit.0 | 2020-06-14 17:13:54.608 | debug | (694289) Caching File /opt/iobroker/cache/686ed27b3ef3efad9c53409a4b864646.mp3 for "ru-RU;23:00" now
sayit.0 | 2020-06-14 17:13:54.046 | debug | (694289) Cache File /opt/iobroker/cache/144c3f20987b16db8d7ac1bac71b8623.mp3 for "ru_YA;23:00" not found
sayit.0 | 2020-06-14 17:13:54.045 | info | (694289) saying: 23:00
sayit.0 | 2020-06-14 17:13:51.043 | debug | (694289) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 3
sayit.0 | 2020-06-14 17:13:51.027 | info | (694289) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3
sayit.0 | 2020-06-14 17:13:32.225 | debug | (694289) Duration "23:00": 0
sayit.0 | 2020-06-14 17:13:32.215 | info | (694289) Copied file "/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3" to "/opt/iobroker/cache/686ed27b3ef3efad9c53409a4b864646.mp3"
sayit.0 | 2020-06-14 17:13:32.212 | debug | (694289) Caching File /opt/iobroker/cache/686ed27b3ef3efad9c53409a4b864646.mp3 for "ru-RU;23:00" now
sayit.0 | 2020-06-14 17:13:31.635 | debug | (694289) Cache File /opt/iobroker/cache/144c3f20987b16db8d7ac1bac71b8623.mp3 for "ru_YA;23:00" not found
sayit.0 | 2020-06-14 17:13:31.635 | info | (694289) saying: 23:00
sayit.0 | 2020-06-14 17:13:23.091 | debug | (694289) Duration "23:00": 0
sayit.0 | 2020-06-14 17:13:23.079 | info | (694289) Copied file "/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3" to "/opt/iobroker/cache/686ed27b3ef3efad9c53409a4b864646.mp3"
sayit.0 | 2020-06-14 17:13:23.072 | debug | (694289) Caching File /opt/iobroker/cache/686ed27b3ef3efad9c53409a4b864646.mp3 for "ru-RU;23:00" now
sayit.0 | 2020-06-14 17:13:22.601 | debug | (694289) Cache File /opt/iobroker/cache/144c3f20987b16db8d7ac1bac71b8623.mp3 for "ru_YA;23:00" not found
sayit.0 | 2020-06-14 17:13:22.600 | info | (694289) saying: 23:00
sayit.0 | 2020-06-14 17:13:19.599 | debug | (694289) Duration "/opt/iobroker/node_modules/iobroker.sayit/gong.mp3": 3
sayit.0 | 2020-06-14 17:13:19.583 | info | (694289) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

**Comment by ded000** [comment]
((

**Comment by Apollon77** [comment]
Interesting. The language is different when caching the file or when writing it and this is the reason.

**Comment by ded000** [comment]
There are no problems with google.RU.

**Comment by ded000** [comment]
|   |   |  
-- | -- | -- | --
sayit.0 | 2020-06-15 01:07:21.587 | debug | (754120) Duration "777": 0
sayit.0 | 2020-06-15 01:07:21.579 | info | (754120) Copied file "/opt/iobroker/node_modules/iobroker.sayit/lib/../sayit.0.say.mp3" to "/opt/iobroker/cache/8d4a45128b21ae95edfbbdd10dbfe1fe.mp3"
sayit.0 | 2020-06-15 01:07:21.578 | debug | (754120) Caching File /opt/iobroker/cache/8d4a45128b21ae95edfbbdd10dbfe1fe.mp3 for "ru-RU;777" now

**Comment by Apollon77** [comment]
The relevant part is:

```
sayit.0 | 2020-06-14 17:13:23.072 | debug | (694289) Caching File /opt/iobroker/cache/686ed27b3ef3efad9c53409a4b864646.mp3 for "ru-RU;23:00" now
-- | -- | -- | --
sayit.0 | 2020-06-14 17:13:22.601 | debug | (694289) Cache File /opt/iobroker/cache/144c3f20987b16db8d7ac1bac71b8623.mp3 for "ru_YA;23:00" not found
```

He is searching for a cache file which is different from the one he then writes to chache the file ... 

Will check
