### ISSUE TITLE
Future version warnung from js-controller

### ISSUE THREAD

**Issue by realwax** [ioBroker/ioBroker.sayit#89]
sayit.0 | 2020-04-30 13:15:21.320 | warn | readFile will not read this file (tts.userfiles/gong.mp3) in future versions: sayit.0 is not an object of type "meta"
-- | -- | -- | --
sayit.0 | 2020-04-30 13:15:21.183 | warn | readFile will not read this file (tts.userfiles/scifi.mp3) in future versions: sayit.0 is not an object of type "meta"

**Comment by Apollon77** [comment]
--> https://github.com/ioBroker/ioBroker.js-controller/issues/883
