### ISSUE TITLE
Keine Funktion mehr mit Sonos

### ISSUE THREAD

**Issue by speedmaster1** [ioBroker/ioBroker.sayit#91]
Ich habe leider das Problem das meine Sprachausgabe über den Sayit Adapter plötzlich nicht mehr funktioniert. Hat jemand ähnliche Probleme? Meine Sonos Boxen bleiben stumm, auch über einen direkten Sprachbefehl keine Ansage.

**Comment by GermanBluefox** [comment]
Bitte bei sonos ein Issue erzeugen.

**Comment by nicoh88** [comment]
@speedmaster1 Konntest du dein Problem lösen?

Habe hier das gleiche Problem. Habe bei Sonos ein Issue geöffnet:
https://github.com/ioBroker/ioBroker.sonos/issues/73
