### ISSUE TITLE
mp3 wird nicht immer erzeugt.

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sayit#93]
Hallo,
bei Einstellung "browser" wird ja eine mp3 Datei erzeugt/gespeichert unter:
C:\iobroker\Home\node_modules\iobroker.sayit

Diese Speicherung erfolgt nicht zuverlässig. Manchmal wird die Datei gar nicht erzeugt bzw. überschrieben.

Dies war bei meinem alten System mit win7 so. Und auch jetzt bei menem neuen Rechner win10 ist es ebenfalls so.
und dieses Phänomen ist auch schon länger so. Mein 1. Beitrag in iob ist von Anfang 2019 !

Bitte Fehler bereinigen.
Danke.

mfg
Dieter

**Comment by Apollon77** [comment]
Bitte Debug Log posten

**Comment by bahnuhr** [comment]
Folgender Script Befehl ausgeführt:
setState('sayit.2.tts.text', "alles wird gespeichert"); 


Im log kam dann:
`
sayit.2 | 2020-07-17 07:42:45.744 | debug | (8176) Duration "alles wird gespeichert": 2
-- | -- | -- | --
sayit.2 | 2020-07-17 07:42:45.721 | info | (8176) Copied file "C:\iobroker\node_modules\iobroker.sayit\lib/../sayit.2.say.mp3" to "C:\iobroker\cache\7c606e373bf3eec118e52c691341f4ae.mp3"
sayit.2 | 2020-07-17 07:42:45.471 | info | (8176) saying: alles wird gespeichert
`
Die Datei wurde gespeichert.
Also noch ein Versuch mit.
setState('sayit.2.tts.text', "Test Test"); 

Im log kam dann:
`
sayit.2 | 2020-07-17 07:45:56.804 | debug | (8176) Duration "Test Test": 0
-- | -- | -- | --
sayit.2 | 2020-07-17 07:45:56.803 | error | (8176) File error: Error: EBUSY: resource busy or locked, open 'C:\iobroker\node_modules\iobroker.sayit\sayit.2.say.mp3'
sayit.2 | 2020-07-17 07:45:52.278 | info | (8176) saying: Test Test
`

Und dies hat nicht geklappt !!

**Comment by Apollon77** [comment]
> File error: Error: EBUSY: resource busy or locked

Das ist doch eindeutig ... Irgendwie erlaubt dein Filesystem in dem augenblick keine Änderung an dem File. Jetzt ist die Frage: Warum. Läuft da vllt was parallel? Virenscanner?

**Comment by bahnuhr** [comment]
Ja Ingo,
sieht für mich auch so aus.
Lösung hab ich aber keine.
Und ja, virenscanner läuft (antivir).
Da ich aber nicht der einzige mit dem Problem bin (siehe Forum) glaube ich aber nicht, dass es antivir sein soll.

Oder anders rum.
Ich schalt antivir mal aus und probiere es noch mal.

**Comment by bahnuhr** [comment]
So antivir aus.
Fehler bleibt weiterhin:
busy or locked

**Comment by Apollon77** [comment]
Kann es sein das es gerade gelesen wirde um abgespielt zu werden und du daher nicht schreiben darfst? Wer nutzt das File denn und wie?

**Comment by bahnuhr** [comment]
Nein, es wird nicht abgespielt.
Das File wird nicht genutzt.

Ich lasse nur dies als script laufen:
setState('sayit.2.tts.text', "Test Test");

Und dabei kommt der Fehler.

Und wie du hier siehst:
https://forum.iobroker.net/topic/33688/bug-sayit-funktioniert-unter-win-nicht-zuverl%C3%A4ssig
betrifft es wohl auch andere.

Der BUG (wenn es denn einer ist) ist bei mir seit Anfang an (mehrere Jahre).

**Comment by bahnuhr** [comment]
Vielleicht hilft dies zur Fehlersuche:

- sayit Instanz neu gestartet
- in sayit debug eingeschaltet.

```
setState('sayit.2.tts.text', "a b c "); 

```

Im log kommt:
```
sayit.2	2020-07-27 09:17:53.686	debug	(6940) Duration "a b c ": 0
sayit.2	2020-07-27 09:17:53.685	error	(6940) File error: Error: EBUSY: resource busy or locked, open 'C:\iobroker\node_modules\iobroker.sayit\sayit.2.say.mp3'
sayit.2	2020-07-27 09:17:53.582	debug	(6940) Cache File C:\iobroker\cache\97531baa945533aab17f6d0f5c9cba36.mp3 for "de;a b c " not found
sayit.2	2020-07-27 09:17:53.581	info	(6940) saying: a b c
```

Fragen:
Wieso findet er ein cache file nicht?
wieso busy or locked ?

**Comment by bahnuhr** [comment]
hier die Lösung:
https://forum.iobroker.net/topic/33688/gel%C3%B6st-bug-sayit-funktioniert-bei-win-nicht-zuverl%C3%A4ssig/89
